libs/configuration-variables-resolver/composer.json

Make variables resolver usable in apps with php8

configuration-variables-resolver: require php >=7.4

---

libs/staging-provider/src/Staging/Workspace/SnowflakeWorkspaceStaging.php
libs/staging-provider/tests/Provider/WorkspaceStagingProviderTest.php
libs/staging-provider/tests/Staging/Workspace/SnowflakeWorkspaceStagingTest.php
libs/staging-provider/tests/Staging/WorkspaceStagingTest.php
libs/staging-provider/tests/WorkspaceProviderFactory/ExistingDatabaseWorkspaceProviderFactoryTest.php

https://keboola.atlassian.net/browse/PS-3878
Snowpark potrebuje pro pripojeni k Snowflake `account`, ktery my nikde nepouzivame, ale da se odvodit z `host`. Aspon podle oficialni snowflake lib a toho, co jsme videl.

PS-3878 Provide `account` with Snowflake credentials

---

libs/k8s-client/composer.json
libs/k8s-client/src/ClientFacadeFactory/InClusterClientFacadeFactory.php
libs/k8s-client/tests/ClientFacadeFactory/InClusterClientFacadeFactoryTest.php

https://keboola.atlassian.net/browse/PS-3962
Pro GELF logger potrebujeme mit moznost pracovat s jinym namespace, nez ve kterem bezi (logger bezi v `default` namespace, ale Pody, ktere loguji, jsou v `job-queue-jobs`). Zaroven `namespace` je jediny parametr, ktery dava smysl mit moznost pretizit i u te in-cluster auth.
Follow up: https://github.com/keboola/job-queue/pull/209

[k8s-client] PS-3962 Allow setting custom namespace with in-cluster auth

---

libs/input-mapping/composer.json
libs/input-mapping/src/Table/Strategy/ABSWorkspace.php
libs/input-mapping/src/Table/Strategy/AbstractDatabaseStrategy.php
libs/input-mapping/src/Table/Strategy/Synapse.php

V IM jsme volali přímo Storage API abysme se vyhnuli interní implementaci clienta handlování async tásků (čekání na dokončení jobu)
Nová verze https://github.com/keboola/storage-api-php-client/releases/tag/v14.4.0 má už i metody pouze pro zafrontování loadu.

IM - Load table into workspace uses workspace client

---

Dockerfile

Vysla nova verzia xdebugu takze sa automaticky instaluje latest ale ta verzia uz nieje podporovana pre php 7.4

lock version xdebug-3.1.6

---

docker-compose.yml
libs/azure-api-client/azure-pipelines.tests.yml
libs/azure-api-client/composer.json
libs/azure-api-client/src/Authentication/AuthenticatorInterface.php
libs/azure-api-client/src/AzureApiClient.php
libs/azure-api-client/src/GuzzleClientFactory.php
libs/azure-api-client/src/Marketplace/MarketplaceApiClient.php
libs/azure-api-client/src/Marketplace/MeteringServiceApiClient.php
libs/azure-api-client/src/Marketplace/Model/ActivateSubscriptionRequest.php
libs/azure-api-client/src/Marketplace/Model/ReportUsageEventsBatchResult.php
libs/azure-api-client/src/Marketplace/Model/ResolveSubscriptionResult.php
libs/azure-api-client/src/Marketplace/Model/Subscription.php
libs/azure-api-client/src/Marketplace/Model/UsageEventResult.php
libs/azure-api-client/src/ResponseModelInterface.php
libs/azure-api-client/tests/AzureApiClientFunctionalTest.php
libs/azure-api-client/tests/DummyTestResponse.php
libs/azure-api-client/tests/Marketplace/MarketplaceApiClientTest.php
libs/azure-api-client/tests/Marketplace/MeteringServiceApiClientTest.php
libs/azure-api-client/tests/Marketplace/Model/ReportUsageEventsBatchResultTest.php
libs/azure-api-client/tests/Marketplace/Model/ResolveSubscriptionResultTest.php
libs/azure-api-client/tests/Marketplace/Model/SubscriptionTest.php
libs/azure-api-client/tests/Marketplace/Model/UsageEventErrorTest.php
libs/azure-api-client/tests/Marketplace/Model/UsageEventResultTest.php
libs/azure-api-client/tests/Mockserver.php
libs/azure-api-client/tests/ReflectionPropertyAccessTestCase.php

https://keboola.atlassian.net/browse/MAR-17
* mapovani response na objekt presunute do base clienta
* par basic testu, ze se response spravne mapuji a ty API clienti posilaji zhruba ocekavane requesty
Jeste pripravuju ty infection testy, ale kdyz jsem zacal resit ty nepodchycene mutace, zavedlo me to zase na refactoring tech authenticatoru, tak to poslu jeste pozdeji zase jako separatni PR.

MAR-17 Extract Azure API Client to a separate lib (part 3)

---

libs/output-mapping/src/DeferredTasks/LoadTableTaskInterface.php
libs/output-mapping/src/DeferredTasks/TableWriter/AbstractLoadTableTask.php

Fixes: https://keboola.atlassian.net/browse/PST-5
Používá se jenom tu https://github.com/keboola/platform-libraries/blob/dbf111be597cf91e27f067c8078400089f7b4baa/libs/output-mapping/src/DeferredTasks/LoadTableQueue.php#L60
V žádný apce jsem to nenašel. Když to nebude nastavené tak to prostě nově skončí app errorem.

output-mapping - AbstractLoadTableTask - storageJobId is not nullable

---

libs/output-mapping/src/Writer/FileWriter.php
libs/output-mapping/src/Writer/TableWriter.php
libs/output-mapping/tests/Writer/BaseWriterMetadataTest.php
libs/output-mapping/tests/Writer/Redshift/RedshiftWriterWorkspaceTest.php
libs/output-mapping/tests/Writer/Redshift/StorageApiLocalTableWriterRedshiftTest.php
libs/output-mapping/tests/Writer/Redshift/StorageApiSlicedWriterRedshiftTest.php
libs/output-mapping/tests/Writer/SnowflakeWriterMetadataTest.php
libs/output-mapping/tests/Writer/StorageApiFileWriterTest.php
libs/output-mapping/tests/Writer/StorageApiHeadlessWriterTest.php
libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php
libs/output-mapping/tests/Writer/StorageApiSlicedWriterTest.php
libs/output-mapping/tests/Writer/TableDefinitionTest.php
libs/output-mapping/tests/Writer/Workspace/AbsWriterWorkspaceTest.php
libs/output-mapping/tests/Writer/Workspace/SynapseWriterWorkspaceTest.php
libs/output-mapping/tests/Writer/Workspace/WriterWorkspaceTest.php

currently it completely skips fileUploads
https://keboola.atlassian.net/browse/PST-773
Protože tohleto https://github.com/keboola/docker-bundle/pull/705 se blbě testuje, tak jsem ten flag udělal povinnej, protože tim odpadá množství chyb, kde se to může zapomenout. Když už to je teda BC break, tak jsem udělal povinnej ten stejnej flag i na tables

add isFailed flag for FileWriter

---

libs/input-mapping/src/Table/Strategy/Local.php

the preserve flag doesn't make any sense for local staging (because it is not persistent), so it is neither true nor false - it is is ignored 
https://keboola.atlassian.net/browse/PST-856

remove confusing warning

---

Dockerfile
azure-pipelines.tags.yml
azure-pipelines.yml
azure-pipelines/jobs/run-tests.yml
docker-compose.yml
libs/api-bundle/azure-pipelines.tests.yml
libs/configuration-variables-resolver/azure-pipelines.tests.yml
libs/input-mapping/azure-pipelines.tests.yml
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceAbsTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceRedshiftTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceSnowflakeTest.php
libs/k8s-client/azure-pipelines.tests.yml
libs/output-mapping/azure-pipelines.tests.yml
libs/permission-checker/azure-pipelines.tests.yml
libs/settle/azure-pipelines.tests.yml
libs/staging-provider/azure-pipelines.tests.yml

Priprava pred https://keboola.atlassian.net/browse/SOX-65
Dalsi zjednoduseni vykopu nove lib. Jelikoz vystupem libky neni Docker image, neni potreba pro kazdou jednotlive buildit separatni Docker image pro CI, vsechno muze v pohode bezet na jednom sdilenem. Novou libku tak neni potreba vubec zavadet do `Dockerfile` a v `docker-compose` staci zalozit service s `workdir`.

Simplify Dockerfile

---

libs/api-bundle/composer.json

Včera jsem udělal bc break do permission checkeru pro schedules, tak jsem ho releasnul jako 1.0

[api-bundle] composer: allow permission checker 1.0

---

libs/configuration-variables-resolver/src/VariablesRenderer/RegexRenderer.php
libs/configuration-variables-resolver/src/VariablesResolver/VaultVariablesResolver.php
libs/configuration-variables-resolver/tests/VariablesRenderer/RegexRendererTest.php
libs/configuration-variables-resolver/tests/VariablesResolver/VaultVariablesResolverTest.php
libs/configuration-variables-resolver/tests/VariablesResolverFunctionalTest.php
libs/configuration-variables-resolver/tests/VariablesResolverTest.php

https://keboola.atlassian.net/browse/SOX-196
Nacitani variables z Vaultu se pusti jen kdyz v configu je neco, co matchne placeholder `{{ vault.* }}`

SOX-196 Load Vault variables only when present in config

---

libs/configuration-variables-resolver/tests/VariablesResolverFunctionalTest.php

Devbranches can't use branch client https://dev.azure.com/keboola-dev/Platform%20Libraries/_build/results?buildId=36052&view=logs&j=a0249fe8-9f74-548a-8eb7-2720f4b41755&t=b2f4e1af-2aa0-5a3d-c143-f86d8e3027d2

fix: variable resolver tests

---

libs/input-mapping/phpstan.neon
libs/input-mapping/src/Helper/FakeDevStorageTableRewriteHelper.php
libs/input-mapping/src/Helper/RealDevStorageTableRewriteHelper.php
libs/input-mapping/src/Helper/TableRewriteHelperInterface.php
libs/input-mapping/src/Reader.php
libs/input-mapping/src/Table/Options/InputTableOptions.php
libs/input-mapping/src/Table/Options/RewrittenInputTableOptions.php
libs/input-mapping/src/Table/Options/RewrittenInputTableOptionsList.php
libs/input-mapping/src/Table/Strategy/ABS.php
libs/input-mapping/src/Table/Strategy/ABSWorkspace.php
libs/input-mapping/src/Table/Strategy/AbstractDatabaseStrategy.php
libs/input-mapping/src/Table/Strategy/AbstractStrategy.php
libs/input-mapping/src/Table/Strategy/Local.php
libs/input-mapping/src/Table/Strategy/S3.php
libs/input-mapping/src/Table/Strategy/Synapse.php
libs/input-mapping/src/Table/StrategyInterface.php
libs/input-mapping/tests/Functional/DownloadTablesDefaultTest.php
libs/input-mapping/tests/Functional/DownloadTablesRedshiftTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceRedshiftTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceSnowflakeTest.php
libs/input-mapping/tests/Helper/FakeDevStorageTableRewriteHelperTest.php
libs/input-mapping/tests/Helper/RealDevStorageTableRewriteHelperTest.php
libs/input-mapping/tests/Table/Options/InputTableOptionsTest.php
libs/input-mapping/tests/Table/Options/RewrittenInputTableOptionsListTest.php
libs/input-mapping/tests/Table/Options/RewrittenInputTableOptionsTest.php
libs/input-mapping/tests/Table/Strategy/BigQueryTest.php
libs/input-mapping/tests/Table/Strategy/ExasolTest.php
libs/input-mapping/tests/Table/Strategy/LocalStrategyTest.php
libs/input-mapping/tests/Table/Strategy/S3StrategyTest.php
libs/input-mapping/tests/Table/Strategy/TeradataTest.php

Jádro problému je v tom, že je potřeba při fallbacku na default branch upravit všechny getTable cally tak, aby ten fallback dělaly taky. Zhruba takhle https://github.com/keboola/storage-api-php-client/commit/2e31b1e6ef82fbc949b3ee1cbcda8e47baf0ca43#diff-34a77dd53b8861c383400fc88019eb8a04f54f97e17a3bda19221486e2632b2aR176. 
Protože těch volání je tam několik na několika různejch místech, tak to bylo prakticky neotestovatelný to změnit na daným místě. Takže jsem se vydal cestou, vytáhnout tableInfo na jedno místo - do RewrittenInputTableOptions - přidat to do InputTableOptions bylo problematický, protož pak vycházelo tableInfo nullable, anebo by se musel udělat BC break.
Celý je to implementačně far from ideal, snažil jsem se dělat po cestě co nejmíň změn.
Hlavní myšlenka je teda v tom, že …

Fix: getTableCalls

---

libs/azure-api-client/tests/Authentication/Authenticator/ClientCredentialsAuthTest.php
libs/azure-api-client/tests/Authentication/Authenticator/Internal/SystemAuthenticatorResolverTest.php

https://keboola.atlassian.net/browse/SOX-232
By default vsechny testy jedou postupne v jednom procesu, takze zmena envu v jednom testu se propaguje do dalsich. Normalne PHPUnit pousti testy stale ve stejnem poradi a na to to bylo "odladene". Ale Infection by default pousti testy v random poradi, coz vlastne odhalilo skrytou zavislost mezi testama skrz ENV.
* postizeny testy, ktery hodne zavisi na uprave ENV jsem nastavil aby jely v separatnim procesu, tim padem se nijak novlivnuji
* nastavil jsem i PHPunit, aby postel testy v random poradi

SOX-232 Azure Client tests stabilization

---

libs/permission-checker/src/Check/Notification/CanModifySubscriptions.php
libs/permission-checker/tests/Check/Notification/CanModifySubscriptionsTest.php

https://keboola.atlassian.net/browse/SOX-327
V description tasku toho moc nemame :slightly_smiling_face:, ale tak logicky jsem dosle k tomu, ze:
* na SOX projektu
* PM muze delat notifikace na main branch (to uz tam bylo)
* dev/reviewer muze delat notifikace na dev branch
* nikdo nemuze delat notifikace cross-branch
* na ne-SOX muze kdokoliv cokoliv (krome read-only)

SOX-327 [permission-checker] Support for branched/cross-branch notifications

---

libs/permission-checker/src/Check/OAuth/CanModifyAuthorization.php
libs/permission-checker/tests/Check/OAuth/CanModifyAuthorizationTest.php

https://keboola.atlassian.net/browse/GCP-227
Vlastne jen zkopirovany checker pro notifikace:
* na normalni projektu `read-only`/`guest` nesmi manipulovat s autorizaci, jinak kdokoliv muze
* na SOX projektu `production-manager` muze na produkci, `developer`/`reviewer` v dev branch, jinak nikde nikdo

[permission-checker] GCP-227 OAuth permissions checker

---

libs/configuration-variables-resolver/src/ComponentsClientHelper.php
libs/configuration-variables-resolver/src/SharedCodeResolver.php
libs/configuration-variables-resolver/src/VariablesRenderer/MustacheRenderer.php
libs/configuration-variables-resolver/src/VariablesRenderer/RegexRenderer.php
libs/configuration-variables-resolver/src/VariablesResolver.php
libs/configuration-variables-resolver/src/VariablesResolver/ConfigurationVariablesResolver.php
libs/configuration-variables-resolver/src/VariablesResolver/VaultVariablesResolver.php
libs/configuration-variables-resolver/tests/SharedCodeResolverTest.php
libs/configuration-variables-resolver/tests/VariableResolverTest.php
libs/configuration-variables-resolver/tests/VariablesRenderer/MustacheRendererTest.php
libs/configuration-variables-resolver/tests/VariablesResolver/ConfigurationVariablesResolverTest.php
libs/configuration-variables-resolver/tests/VariablesResolver/VaultVariablesResolverTest.php
libs/configuration-variables-resolver/tests/VariablesResolverFunctionalTest.php
libs/vault-api-client/src/Variables/Model/Variable.php
libs/vault-api-client/src/Variables/VariablesApiClient.php
libs/vault-api-client/tests/Variables/Model/VariableTest.php
libs/vault-api-client/tests/Variables/VariablesApiClientTest.php

https://keboola.atlassian.net/browse/GCP-290
https://keboola.atlassian.net/browse/GCP-291
Sesli se nam ted 2 BC (v ramci cleanupu), tak jsem je odbavil najednou:
* nahrazeni `isEncrypted` property za `flags`
* nahrazeni `/variables/merged/branch` endpointu za `/variables/scoped/branch/{branchId}`
Trochu nesikovne se tam pripletl update code-style, protoze nemame locknutou verzi `keboola/coding-standard`. Je aspon izolovany do samostatnyho commitu.
Vydam to jako
* major verzi `vault-api-client`
* patch verzi `configuration-variables-resolver`
Potom je potreba updatnout v
* `job-runner`
* `job-queue-daemon`
* `data-loader-api`
* `runner-sync-api`

GCP-290 + GCP-291 Use "scoped" endpoint, flags replacing "isEncrypted" property

---

libs/permission-checker/src/Check/OAuth/CanModifyAuthorization.php
libs/permission-checker/tests/Check/OAuth/CanModifyAuthorizationTest.php

https://keboola.atlassian.net/browse/GCP-332
https://keboolaglobal.slack.com/archives/C0551J4J70B/p1695298303430559
Povoluje manipulaci s project-wide (bez `branchId`) OAuth credentials pro production managera.
Navazovat bude PR na update v `oauth-service`

GCP-332 [permission-checker] Project-wide OAuth authorization

---

libs/input-mapping/composer.json

Fixes: https://keboola.atlassian.net/browse/SOX-333
jeste vynucenej update client wrapperu, aby pri zadani neexistujici branche to nepadalo na app erroru

[input-mapping] composer: storage-api-php-client-branch-wrapper >=5.0.1

---

libs/messenger-bundle/src/ConnectionEvent/AuditLog/BaseAuditLogEvent.php
libs/messenger-bundle/src/ConnectionEvent/AuditLog/Organization/ProjectCreatedEvent.php
libs/messenger-bundle/src/ConnectionEvent/AuditLog/Project/ProjectDeletedEvent.php
libs/messenger-bundle/src/ConnectionEvent/AuditLog/Project/ProjectFeatureAddedEvent.php
libs/messenger-bundle/src/ConnectionEvent/AuditLog/Project/ProjectFeatureRemovedEvent.php
libs/messenger-bundle/src/ConnectionEvent/AuditLog/Project/ProjectUndeletedEvent.php
libs/messenger-bundle/src/ConnectionEvent/EventFactory.php
libs/messenger-bundle/src/ConnectionEvent/EventInterface.php
libs/messenger-bundle/src/ConnectionEvent/Exception/EventFactoryException.php
libs/messenger-bundle/src/ConnectionEvent/GenericEvent.php
libs/messenger-bundle/src/ConnectionEvent/Serializer/AwsSqsSerializer.php
libs/messenger-bundle/src/ConnectionEvent/Serializer/AzureServiceBusSerializer.php
libs/messenger-bundle/tests/ConnectionEvent/AuditLog/Organization/ProjectCreatedEventTest.php
libs/messenger-bundle/tests/ConnectionEvent/AuditLog/Project/ProjectDeletedEventTest.php
libs/messenger-bundle/tests/ConnectionEvent/AuditLog/Project/ProjectFeatureAddedEventTest.php
libs/messenger-bundle/tests/ConnectionEvent/AuditLog/Project/ProjectFeatureRemovedEventTest.php
libs/messenger-bundle/tests/ConnectionEvent/AuditLog/Project/ProjectUndeletedEventTest.php
libs/messenger-bundle/tests/ConnectionEvent/Serializer/AwsSqsSerializerTest.php
libs/messenger-bundle/tests/ConnectionEvent/Serializer/AzureServiceBusSerializerTest.php

https://keboola.atlassian.net/browse/SOX-423
Tohle je 1:1 vykopirovany kod ze `sandboxes-service`. Jedine, co jsem zmenil, je namespace.
Samostatne to je takle samozrejme nefunkcni. Ale prislo mi rozumny PR oddelit to, co 1:1 odnekud kopiruju, nemenim a uz to v ty podobne nekde review proslo a to, co je nove a opravdu potrebuje kontrolu (https://github.com/keboola/platform-libraries/pull/165)
CI je ocekavane, ze je tu cervene. Mergovat budu pak cely SOX-423 v ramci https://github.com/keboola/platform-libraries/pull/165

SOX-423 [messenger-bundle] Copy code from `sandboxes-service`

---

libs/messenger-bundle/src/DependencyInjection/KeboolaMessengerExtension.php
libs/messenger-bundle/tests/DependencyInjection/KeboolaMessengerExtensionTest.php
libs/messenger-bundle/tests/FakeDoctrineBundle.php

https://keboola.atlassian.net/browse/SOX-451
MySQL automaticky zavira spojeni po nejake dobe neaktivity. Jelikoz consumer muze celkem dlouho cekat, nez prijde nova message, je potreba to mit osetrene. Je to bezna situace, takze na to existuje oficialni reseni v podobe middleware https://symfony.com/doc/current/messenger.html#middleware-for-doctrine

SOX-451 Add Doctrine ping middleware

---

libs/permission-checker/src/Check/Notification/CanModifySubscriptions.php
libs/permission-checker/src/Check/OAuth/CanModifyAuthorization.php
libs/permission-checker/src/Check/Vault/CanModifyVariable.php
libs/permission-checker/tests/Check/Notification/CanModifySubscriptionsTest.php
libs/permission-checker/tests/Check/OAuth/CanModifyAuthorizationTest.php
libs/permission-checker/tests/Check/Vault/CanModifyVariableTest.php

https://keboola.atlassian.net/browse/SOX-387
Nakonec se to ukazalo jako ne zase tak velky problem, jak jsme se na zacatku bali.
SOX (protected default branch) situace by mely byt v pohode, vude mame "default deny" a jen explicitne vyjmenovane situace, kdy danou akci dovolujeme. Problem byly nektere ne-SOX checky, kde mame "default allow" behaviour + seznam roli, ktery to naopak nesmi delat. Tam jsme se obcas zapomneli zamyslet nad tokeny bez role a pripadne guest, ktery je takova variace na read-only (https://help.keboola.com/management/project/users/#user-roles).
Pri vymysleni jsem si to zkusil trosku zjednodusit a uvazoval jsem, ze token s roli = user (vic/mene clovek co tuka pres UI), token bez role = nejaka automatizace/integrace pres API.

SOX-387 Adjust no role & guest role permissions

---

libs/output-mapping/composer.json

Min version updated to 14.12 _(has fixed re-upload of files on GCS)_ https://github.com/keboola/storage-api-php-client/releases/tag/v14.12.0

[output-mapping] composer: storage-api-client 14.12

---

libs/api-bundle/README.md
libs/api-bundle/src/Security/AttributeAuthenticator.php
libs/api-bundle/tests/Security/AttributeAuthenticatorTest.php

Opravuje podporu vice auth attributu na jednom controlleru. `AttributeAuthenticator` na to byl od zacatku designovany, ale evidentne jsem to zapomnel otestovat :facepalm:
```
#[StorageApiTokenAuth(features: ['feat-a'])]
#[StorageApiTokenAuth(isAdmin: true)] // tohle realne nemame implementovany, ale tak pro ilustraci
class Controller {
public function __invoke() {
// povoli token, ktery ma `feat-a` NEBO je admin token
}
}
#[ManageApiTokenAuth(scopes: ['something:manage'])]
#[StorageApiTokenAuth]
class Controller {
public function __invoke(
string $entityId,
#[CurrentUser] TokenInterface $token,
) {
// povoli manage token se scope `something:manage` NEBO libovolny storage token a controller si pak muze doresit detaily
$entity = $this->fetchEntity($entityId);
if ($token instanceof …
```

[api-bundle] Fix support for multiple auth attributes on single controller

---

libs/api-bundle/README.md
libs/api-bundle/src/DependencyInjection/KeboolaApiExtension.php
libs/api-bundle/src/Resources/config/api_bundle.php

Podpora ENV variables v configu neni bohuzel v Symfony uplne idealni a obcas vyzaduje nejake workaroundy. Tady byly nakonec 2 moznosti jak vyresit, aby `default_service_dns_type` sel nastavit pres ENV:
* odebrat z configu `cannotBeEmpty`
* vzdycky poskytnout nejakou validni default hodnotu
Pokud bysme povolili prazdnou hodnotu, musel by se pro to upravit konstruktor `ServiceClient`, coz mi neprislo spravny, protoze neco, co jde zvalidovat uz pri startu appky by se validovalo az za behu. Takze jsem radeji sel druhou cestou a zdokumentoval, ze pri pouziti ENV je potreba poskytnout default.

[api-bundle] Allow setting `default_service_dns_type` using ENV vars

---

libs/input-mapping/composer.json
libs/output-mapping/composer.json

Temporary workaround for publish pipeline

Lock storage-api-client on v14.16

---

libs/input-mapping/composer.json
libs/output-mapping/composer.json

Remove temporary workaround for publish pipeline
(Rollback of this issue: https://keboolaglobal.slack.com/archives/C055HSMKX51/p1712323408026709?thread_ts=1712322947.986839&cid=C055HSMKX51)

Remove storage-api-client lock on v14.16

---

libs/service-client/src/Service.php
libs/service-client/src/ServiceClient.php
libs/service-client/tests/ServiceClientTest.php
libs/service-client/tests/ServiceTest.php

https://keboola.atlassian.net/browse/PST-1629
Pridani podpory pro Job Queue Internal API.
K8S service je v `default` namespace, jmenuje se `job-queue-internal-api`, public DNS to nema.

PST-1629 Add support for job queue internal API

---

libs/output-mapping/src/Storage/AbstractTableStructureModifier.php
libs/output-mapping/src/Storage/TableStructureModifier.php
libs/output-mapping/src/Storage/TableStructureModifierFromSchema.php
libs/output-mapping/src/Storage/TableStructureValidator.php
libs/output-mapping/src/Writer/Helper/PrimaryKeyHelper.php
libs/output-mapping/tests/Storage/TableStructureValidatorTest.php
libs/output-mapping/tests/Writer/Helper/PrimaryKeyHelperTest.php

Fixes: https://keboola.atlassian.net/browse/PST-1910
Change store nově má nastavený PK jen při změně. Tak jak jsme se bavili v pátek. Pak by se případně mohlo vrátit i to `hasChanges` pokud je k něčemu potřeba.

Output Mapping - PK in TableChangesStore only if changed

---

README.md
libs/input-mapping/src/Table/Options/InputTableOptions.php
libs/input-mapping/src/Table/Strategy/S3.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceSnowflakeAdaptiveTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceSnowflakeTest.php
libs/input-mapping/tests/Table/Options/InputTableOptionsTest.php

- WS load nove uz podporuje i adaptivni `changed_since`
V runneru by se ten state mel updatnout normalne, neni potreba doimplementovat:
https://github.com/keboola/docker-bundle/blob/main/src/Docker/Runner.php#L505

PST-1967: feat (input-mapping): add ADAPTIVE_INPUT_MAPPING_VALUE option to WS load

---

libs/input-mapping/src/Table/Result.php

Part of https://keboola.atlassian.net/browse/PST-1689
Abych v job runneru nemel phpstan errory
```
Parameter #1 $tableInfo of static method App\Helper\TableInfoConverter::convertTableInfoToTableResult() expects Keboola\InputMapping\Table\Result\TableInfo,  
mixed given. 
```

[input-mapping] Table/Result::getTables() return type phpdoc

---

libs/permission-checker/src/Check/SandboxesService/CanManageApp.php
libs/permission-checker/tests/Check/SandboxesService/CanManageAppTest.php

App id je vždy integer - https://github.com/keboola/sandboxes-service/pull/237#discussion_r1747377381

fix(permission-checker): Use integer for app id

---

libs/service-client/src/Service.php
libs/service-client/tests/ServiceClientTest.php
libs/service-client/tests/ServiceTest.php

Nahodou jsem narazil na to, ze mame prohozeny namespace u `billing` a `buffer` servis (`billing` bezi v `default` NS, `buffer` ve svym NS).

fix[service-client]: Fix switched namespace of billing & buffer services

---

libs/output-mapping/azure-pipelines.tests.yml
libs/output-mapping/src/Exception/TableNotFoundException.php
libs/output-mapping/src/Storage/AbstractTableStructureValidator.php
libs/output-mapping/src/Storage/TableStructureValidator.php
libs/output-mapping/src/Storage/TableStructureValidatorFactory.php
libs/output-mapping/src/Storage/TypedTableStructureValidator.php
libs/output-mapping/src/TableLoader.php
libs/output-mapping/tests/Storage/TableStructureValidatorFactoryTest.php
libs/output-mapping/tests/Storage/TableStructureValidatorTest.php
libs/output-mapping/tests/Storage/TypedTableStructureValidatorTest.php

https://keboola.atlassian.net/browse/PST-1775

Split TableStructureValidator

---

azure-pipelines/jobs/run-tests.yml
libs/output-mapping/azure-pipelines.tests.yml
libs/output-mapping/phpunit.xml.dist
libs/output-mapping/tests/InitSynapseStorageClientTrait.php
libs/output-mapping/tests/Writer/File/Strategy/ABSWorkspaceTest.php
libs/output-mapping/tests/Writer/Table/Source/AbsWorkspaceItemSourceFactoryTest.php
libs/output-mapping/tests/Writer/Workspace/AbsWriterWorkspaceTest.php
libs/output-mapping/tests/Writer/Workspace/SynapseWriterWorkspaceTest.php
libs/staging-provider/azure-pipelines.tests.yml

Mělo by fixovat build na CI
- output-mapping - přesunutí testů souvisejících se synapse do samostatné suity
- stagin-providier - synapse testy se pousti jen kdyz je nastavena variable

[output-mapping] abs tests moved to own suite for azure

---

libs/output-mapping/tests/LoadTableTaskCreatorTest.php
libs/output-mapping/tests/Needs/TestSatisfyer.php

Po uprave https://github.com/keboola/platform-libraries/pull/343 se mergoval nerebasnuty PR s paratestem https://github.com/keboola/platform-libraries/pull/346 ktery meni logiku pro generovani nazvu testovacich resourcu.
Tahle uprava to fixuje, aby prochazela pipeline.

[output-mapping] LoadTableTaskCreatorTest table ids asserts fixup

---

libs/k8s-client/src/BaseApi/PodWithLogStream.php
libs/k8s-client/src/ClientFacadeFactory/ClientConfigurator.php
libs/k8s-client/src/ClientFacadeFactory/GenericClientFacadeFactory.php
libs/k8s-client/src/ClientFacadeFactory/InClusterClientFacadeFactory.php
libs/k8s-client/src/ClientFacadeFactory/Token/InClusterToken.php
libs/k8s-client/src/ClientFacadeFactory/Token/StaticToken.php
libs/k8s-client/src/ClientFacadeFactory/Token/TokenInterface.php
libs/k8s-client/src/Guzzle/AuthMiddleware.php
libs/k8s-client/tests/ApiClient/BaseClusterApiClientTestCase.php
libs/k8s-client/tests/ApiClient/BaseNamespaceApiClientTestCase.php
libs/k8s-client/tests/ApiClient/EventsApiClientTest.php
libs/k8s-client/tests/BaseApi/PodWithLogStreamTest.php
libs/k8s-client/tests/ClientFacadeFactory/ClientConfiguratorTest.php
libs/k8s-client/tests/ClientFacadeFactory/InClusterClientFacadeFactoryTest.php
libs/k8s-client/tests/ClientFacadeFactory/Token/InClusterTokenTest.php
libs/k8s-client/tests/ClientFacadeFactory/Token/StaticTokenTest.php
libs/k8s-client/tests/Guzzle/AuthMiddlewareTest.php

https://keboola.atlassian.net/browse/PST-2391
Token, ktery K8S token provisionuje jako file ma omezenou platnost (1 hodinu). K8S automaticky refreshuje token cca 10 minut pred expiraci, takze my si potrebujeme token prubezne refreshovat z file systemu.
Puvodni K8S client prebira token jako string v constructoru a jeho re-inicializace mi prisla unreal. Takze jako nejjednodussi reseni se mi ukazalo token vubec nepredavat a misto toho tam injectnout vlastni `AuthMiddleware`, ktera resi autentizaci.
To, jak dlouho pred expiraci se token refreshne, neni nikde zdokumentovany a nejspis to zalezi na implementaci K8S, takze se muze lisit mezi cloudama, ale experimentalne jsem overil, ze AWS, AZ i GCP to dela cca 50 minutach, takze refresh jsem nastavil kazdych 5 minut, abysme se zarucene trefili …

feat[k8s-client]: Periodically reload K8S token

---

libs/output-mapping/src/Configuration/Table/BaseConfiguration.php
libs/output-mapping/tests/Configuration/Table/BaseConfigurationTest.php

Fixes: https://keboola.atlassian.net/browse/PST-2398
Oprava pro https://github.com/keboola/platform-libraries/pull/362
> The child config "workspace_id" under "container.storage.output.tables.0.delete_where.0.where_filters.0.values_from_workspace" must be configured.

[output-mapping] allow values_from_workspace without workspace id

---

libs/configuration-variables-resolver/src/UnifiedConfigurationResolver.php
libs/configuration-variables-resolver/src/UnifiedConfigurationResolverFactory.php

Viz. dnešní call kolem testů, tj. nejde namockovat readonly class v rámci testů na daemonovi, takže tímhle to obejdeme.

Make unified configuration resolver related classes non-readonly

---

libs/messenger-bundle/src/ConnectionEvent/ApplicationEvent/GenericApplicationEvent.php
libs/messenger-bundle/src/ConnectionEvent/ApplicationEvent/Storage/DevBranchCreatedEvent.php
libs/messenger-bundle/src/ConnectionEvent/ApplicationEvent/Storage/DevBranchDeletedEvent.php
libs/messenger-bundle/tests/ConnectionEvent/ApplicationEvent/ApplicationEventFactoryTest.php
libs/messenger-bundle/tests/ConnectionEvent/ApplicationEvent/ApplicationEventTest.php
libs/messenger-bundle/tests/ConnectionEvent/ApplicationEvent/Storage/DevBranchCreatedEventTest.php
libs/messenger-bundle/tests/ConnectionEvent/ApplicationEvent/Storage/DevBranchDeletedEventTest.php

https://keboola.atlassian.net/browse/PST-2512
https://keboolaglobal.slack.com/archives/C08HLV1E5LH/p1741873983545469?thread_ts=1741854899.043299&cid=C08HLV1E5LH
@zajca v ramci reseni performance eventu v [#prod_24_7___inc_21370](https://keboolaglobal.slack.com/archives/C08HLV1E5LH) rusi jejich `int $id` a nahrazuje to za `string $uuid`. To potrebujem reflektovat v nasi reprezentaci Connection eventu (a pak updatnout ve vsech appkach, kde se to pouizva).

PST-2512 [messenger-bundle] Replace event ID with UUID

---

libs/configuration-variables-resolver/composer.json

Povoleni verzu 16 & 17 `keboola/storage-api-client`. Jsou to sice major verze, ale zadna z breaking-changes se netyka pouziti v `configuration-variables-resolver`

[configuration-variables-resolver]: Allow keboola/storage-api-client version 16 & 17

---

libs/staging-provider/src/Provider/NewWorkspaceProvider.php
libs/staging-provider/tests/Provider/NewWorkspaceProviderTest.php

https://keboola.atlassian.net/browse/PAT-255
Tak pro velky uspech jeste zpatky na stromy. Vratil jsem `getBackendSize()` a `getBackendType()` na `NewWorkspaceProvider`, aby delaly inicializaci WS a vracely diky tomu hodnoty, ktery o WS tvrdi Connection.
V `docker-bundle` jsem narazil na test, ktery na tom failoval v situaci, kdy `WorkspaceBackendConfig` mel prazny `backendSize`. Connection v tu chvili totiz vraci default `small`.

PAT-255 [staging-provider]: Getters on NewWorkspaceProvider must return real workspace values

---

libs/input-mapping/src/Table/Result/TableInfo.php
libs/output-mapping/src/Table/Result.php
libs/output-mapping/src/Table/Result/Metrics.php

Poladeni Result classes na IM/OM:
* Doplneni chybejich typu u poli
* Prehozeni zbyvajicich `Generator` na `array` (kdysi jsem to uz menil na IM, ale neco malo zustalo jeste na OM)

[input-mapping,outupt-mapping]: Fix missing return types of lists in results

---

docker-compose.yml
docker/php/php.ini
libs/doctrine-retry-bundle/composer.json
libs/doctrine-retry-bundle/src/DependencyInjection/Compiler/ConfigureDbalRetryProxyPass.php
libs/doctrine-retry-bundle/tests/Database/ConnectionWithRetryTest.php
libs/doctrine-retry-bundle/tests/FailingRetryProxy.php
libs/doctrine-retry-bundle/tests/MysqlProxyTestTrait.php

vydal bych to jako major verzi, je tam BC break v DBAL a dělat to tak, aby to supportovalo obě verze mě přijde hroznej vofrk na to jak málo se takhle věc updatuje

[doctrine-retry-bundle] update to PHP 8.4

---

libs/messenger-bundle/composer.json

Part of https://keboola.atlassian.net/browse/AJDA-582
aymdev/messenger-azure-bundle 2 je kompatibilní se symfony 7, která je v AI service

[messenger-bundle] use aymdev/messenger-azure-bundle upstream instead of fork

---

Dockerfile
docker-compose.yml
libs/input-mapping/composer.json
libs/input-mapping/src/Configuration/Table.php
libs/input-mapping/src/Staging/StrategyFactory.php
libs/input-mapping/src/Table/Options/InputTableOptions.php
libs/input-mapping/src/Table/Options/RewrittenInputTableOptions.php
libs/input-mapping/tests/AbstractTestCase.php
libs/input-mapping/tests/Configuration/TableConfigurationTest.php
libs/input-mapping/tests/Functional/DownloadTablesOutputTest.php
libs/input-mapping/tests/Staging/StrategyFactoryTest.php
libs/input-mapping/tests/Table/Options/RewrittenInputTableOptionsTest.php

JIRA: DMD-289
storage hase new option for table exports fileType: {csv,parquet}
add corresponding file_type option for input mapping
--
waiting for:
https://github.com/keboola/storage-api-php-client/pull/1543
https://github.com/keboola/platform-libraries/pull/409
to be released and deployed

DMD-289 add file_type support for file input mapping

---

libs/output-mapping/src/DeferredTasks/LoadTableQueue.php
libs/output-mapping/tests/DeferredTasks/LoadTableQueueTest.php

In Ai Service "SQL Editor" we need to get to the Storage jobs. 
- add getter method getLoadTableTasks on LoadTableQueue
https://keboolaglobal.slack.com/archives/C08AG6VQWG6/p1756316998873219?thread_ts=1756300066.458899&cid=C08AG6VQWG6

AJDA-922: feat (output-mapping): add method LoadTableQueue::getLoadTableTasks()

---

libs/messenger-bundle/src/ConnectionEvent/AuditLog/Admin/AdminDeletedEvent.php
libs/messenger-bundle/src/ConnectionEvent/AuditLog/AuditEventFactory.php
libs/messenger-bundle/tests/ConnectionEvent/AuditLog/Admin/AdminDeletedEventTest.php

**Summary:**
Implements a new audit log event for admin deletion operations in the messenger-bundle library.
**Changes:**
- **Added** `AdminDeletedEvent` class to handle admin deletion audit events
- **Extended** `AuditEventFactory` to support the new `auditLog.admin.deleted` event type
- **Added** comprehensive unit tests for the new event class
**Details:**
- New event captures admin ID, name, and email from both the performing admin and the deleted admin
- Follows existing audit log event patterns with proper serialization/deserialization
- Includes full test coverage with positive and negative test cases
- Event name: `auditLog.admin.deleted`
**Ticket:** [AJDA-586](https://keboola.atlassian.net/browse/AJDA-586)
[AJDA-586]: https://keboola.atlassian.net/browse/AJDA-586?atlOrigin=eyJpIjo …

feat[messenger-bundle]: AJDA-586 add admin deleted event from audit log
