keboola/platform-libraries

azure-pipelines.yml

Staging provider - split repo

---

azure-pipelines.tags.yml
azure-pipelines.yml

Revert "output-mapping - split repo temporary removed for first import"

---

azure-pipelines.tags.yml
azure-pipelines.yml

jdu prejmenovat tohle https://github.com/keboola/configuration-variables-resolver-new az mergnem tenhle PR

PS 3616 rename var resolver repo

---

libs/configuration-variables-resolver/composer.json
libs/configuration-variables-resolver/tests/SharedCodeResolverTest.php
libs/input-mapping/composer.json
libs/output-mapping/composer.json
libs/staging-provider/composer.json

Fixes: https://keboola.atlassian.net/browse/PS-3520 + https://keboola.atlassian.net/browse/PS-3521 + https://keboola.atlassian.net/browse/PS-3527

Update Storage API client to version that supports GCS

---

libs/configuration-variables-resolver/.gitignore
libs/configuration-variables-resolver/composer.json
libs/configuration-variables-resolver/phpunit.xml.dist
libs/configuration-variables-resolver/src/VariableResolver.php
libs/configuration-variables-resolver/src/VariablesContext.php
libs/configuration-variables-resolver/tests/VariableResolverTest.php
libs/configuration-variables-resolver/tests/bootstrap.php
libs/staging-provider/composer.json

https://keboola.atlassian.net/browse/PS-3031

Fix processing of variables with integer name or value

---

libs/output-mapping/src/DeferredTasks/LoadTableQueue.php
libs/output-mapping/src/Table/Result.php
libs/output-mapping/src/Table/Result/Metrics.php
libs/output-mapping/src/Table/Result/TableMetrics.php
libs/output-mapping/tests/DeferredTasks/LoadTableQueueTest.php
libs/output-mapping/tests/Table/Result/MetricsTest.php
libs/output-mapping/tests/Table/Result/TableMetricsTest.php
libs/output-mapping/tests/Table/ResultTest.php

Fixes: https://keboola.atlassian.net/browse/PS-3495

Output Mapping - Load result with metrics

---

Dockerfile
docker-compose.yml
libs/logging-bundle/azure-pipelines.tests.yml
libs/logging-bundle/composer.json

Odin se obaval, jestli ty kernel veci budou fungovat i pod Symfony 6.x, tak to pojdme vyzkouset :slightly_smiling_face: 
Je to zase par veci dohromady, pokusil jsem se to vsechno popsat v commentech primo u kodu.

Test logging-bundle against multiple versions of Symfony

---

azure-pipelines.tags.yml
azure-pipelines.yml
bin/ci-find-changes.sh
docker-compose.yml
libs/k8s-client/.gitignore
libs/k8s-client/LICENSE
libs/k8s-client/README.md
libs/k8s-client/azure-pipelines.tests.yml
libs/k8s-client/composer.json
libs/k8s-client/phpcs.xml
libs/k8s-client/phpstan.neon
libs/k8s-client/phpunit.xml.dist
libs/k8s-client/src/ApiClient/PodsApiClient.php
libs/k8s-client/src/ApiClient/SecretsApiClient.php
libs/k8s-client/src/ClientFacadeFactory/GenericClientFacadeFactory.php
libs/k8s-client/src/ClientFacadeFactory/InClusterClientFacadeFactory.php
libs/k8s-client/src/Exception/ConfigurationException.php
libs/k8s-client/src/Exception/KubernetesApiFacadeException.php
libs/k8s-client/src/Exception/KubernetesResponseException.php
libs/k8s-client/src/Exception/ResourceNotFoundException.php
libs/k8s-client/src/Exception/TimeoutException.php
libs/k8s-client/src/KubernetesApiClient.php
libs/k8s-client/src/KubernetesApiClientFacade.php
libs/k8s-client/src/RetryProxyFactory.php
libs/k8s-client/tests/KubernetesApiClientFacadeTest.php
libs/k8s-client/tests/bootstrap.php
libs/k8s-client/tests/stubs/K8s.stub

https://keboola.atlassian.net/browse/PS-3893
Vytazeni (copy&paste) K8S klienta z `runner-sync-api`, bude potreba v GELF serveru. Kod je vytazeny 1:1, zmeneny je jen namespace a vynechany `DataPlaneClientFacadeFactory`

PS-3893 K8S Client

---

libs/input-mapping/src/Staging/StrategyFactory.php
libs/input-mapping/src/Table/Strategy/BigQuery.php
libs/input-mapping/tests/Staging/StrategyFactoryTest.php
libs/input-mapping/tests/Table/Strategy/BigQueryTest.php
libs/output-mapping/src/Staging/StrategyFactory.php
libs/output-mapping/tests/Staging/StrategyFactoryTest.php
libs/staging-provider/src/InputProviderInitializer.php
libs/staging-provider/src/OutputProviderInitializer.php
libs/staging-provider/src/Staging/Workspace/BigQueryWorkspaceStaging.php
libs/staging-provider/tests/InputProviderInitializerTest.php
libs/staging-provider/tests/OutputProviderInitializerTest.php
libs/staging-provider/tests/Staging/Workspace/BigQueryWorkspaceStagingTest.php
libs/staging-provider/tests/Staging/WorkspaceStagingTest.php

Fixes: https://keboola.atlassian.net/browse/BIG-69
- Input Mapping - https://github.com/keboola/input-mapping-original/pull/118
- Output Mapping - https://github.com/keboola/output-mapping-original/pull/110
- Staging provider - https://github.com/keboola/platform-libraries/commit/0c4ac96277812e7347edcec3e7fe1258df612a07 + https://github.com/keboola/platform-libraries/commit/0a36d4171fda4fbcd3e864326031c700cf2ee933 + https://github.com/keboola/platform-libraries/commit/6b9adfc931138771c7c6076c01fd755a62fcc66c

Support for bigquery staging

---

libs/output-mapping/src/Configuration/Table/Manifest.php
libs/output-mapping/src/Writer/TableWriter.php
libs/output-mapping/tests/Configuration/Table/ManifestTest.php
libs/output-mapping/tests/Configuration/TableTest.php
libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php
libs/output-mapping/tests/Writer/Workspace/WriterWorkspaceTest.php

https://keboola.atlassian.net/browse/PST-543

PST-543 write always

---

libs/staging-provider/src/WorkspaceProviderFactory/ComponentWorkspaceProviderFactory.php
libs/staging-provider/tests/WorkspaceProviderFactory/ComponentWorkspaceProviderFactoryTest.php

https://keboola.atlassian.net/browse/PST-577
[PST-577]: https://keboola.atlassian.net/browse/PST-577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PST-577 Support for use readonly role

---

libs/input-mapping/tests/Functional/DownloadFilesAbsWorkspaceTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceTestAbstract.php
libs/output-mapping/tests/Writer/File/Strategy/ABSWorkspaceTest.php
libs/output-mapping/tests/Writer/Workspace/AbsWriterWorkspaceTest.php
libs/output-mapping/tests/Writer/Workspace/BaseWriterWorkspaceTest.php
libs/staging-provider/composer.json
libs/staging-provider/src/WorkspaceProviderFactory/ComponentWorkspaceProviderFactory.php
libs/staging-provider/tests/OutputProviderInitializerTest.php
libs/staging-provider/tests/WorkspaceProviderFactory/ComponentWorkspaceProviderFactoryTest.php

depends on https://github.com/keboola/platform-libraries/pull/38

create workspace asynchronously

---

libs/output-mapping/src/DeferredTasks/LoadTableQueue.php
libs/output-mapping/tests/DeferredTasks/LoadTableQueueTest.php

Fixes: https://keboola.atlassian.net/browse/PST-6

output-mapping - handle errors on metadata apply

---

libs/output-mapping/src/Writer/Helper/PrimaryKeyHelper.php
libs/output-mapping/src/Writer/TableWriter.php
libs/output-mapping/tests/Writer/Helper/PrimaryKeyHelperTest.php
libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php

Fixes: https://keboola.atlassian.net/browse/PST-540?focusedCommentId=51131

output-mapping - table PK update

---

libs/output-mapping/src/DeferredTasks/LoadTableQueue.php
libs/output-mapping/tests/DeferredTasks/LoadTableQueueTest.php

https://keboola.atlassian.net/browse/PST-588
Depends on https://github.com/keboola/platform-libraries/pull/45

Log extended errors when saving metadata

---

libs/input-mapping/tests/Functional/DownloadFilesAbsWorkspaceTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceTestAbstract.php
libs/output-mapping/tests/Writer/File/Strategy/ABSWorkspaceTest.php
libs/output-mapping/tests/Writer/Workspace/BaseWriterWorkspaceTest.php
libs/staging-provider/src/Provider/WorkspaceStagingProvider.php

https://keboola.atlassian.net/browse/PST-645

asynchronous delete workspace in tests

---

libs/configuration-variables-resolver/composer.json

https://keboola.atlassian.net/browse/PST-596

Allow symfony 6

---

libs/input-mapping/src/Table/Result.php
libs/input-mapping/src/Table/Result/Metrics.php
libs/input-mapping/tests/Functional/DownloadTablesOutputTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceSnowflakeTest.php
libs/output-mapping/src/Table/Result.php

https://keboola.atlassian.net/browse/PST-596

fix initial values and nullability & improved typehints

---

libs/output-mapping/src/DeferredTasks/Metadata/ColumnMetadata.php
libs/output-mapping/tests/DeferredTasks/Metadata/ColumnMetadataTest.php

KBC pri update metadat dela upsert, takze rozdelit to po davkach je ok

output-mapping column metadata bulk size

---

README.md
libs/output-mapping/src/Writer/TableWriter.php
provisioning/ci/synapse-auto-stop/.gitignore
provisioning/ci/synapse-auto-stop/.terraform.lock.hcl
provisioning/ci/synapse-auto-stop/azure.tf
provisioning/ci/synapse-auto-stop/main.tf
provisioning/ci/synapse-auto-stop/runbooks/StopSynapseServer.ps1

Fixes: https://keboola.atlassian.net/browse/PST-574

Synapse shutdown schedule

---

libs/azure-api-client/src/ApiClientFactory/AuthenticatedAzureApiClientFactory.php
libs/azure-api-client/src/ApiClientFactory/AuthorizationHeaderResolver.php
libs/azure-api-client/src/Authentication/AuthenticatorInterface.php
libs/azure-api-client/src/Authentication/ClientCredentialsEnvironmentAuthenticator.php
libs/azure-api-client/src/Authentication/ManagedCredentialsAuthenticator.php
libs/azure-api-client/src/Authentication/TokenResponse.php
libs/azure-api-client/tests/ApiClientFactory/AuthenticatedAzureApiClientFactoryTest.php
libs/azure-api-client/tests/ApiClientFactory/AuthorizationHeaderResolverTest.php
libs/azure-api-client/tests/Authentication/ClientCredentialsEnvironmentAuthenticatorTest.php
libs/azure-api-client/tests/Authentication/ManagedCredentialsAuthenticatorTest.php
libs/azure-api-client/tests/Authentication/TokenResponseTest.php

https://keboola.atlassian.net/browse/PST-689
Depends on https://github.com/keboola/platform-libraries/pull/57
Udelal jsme to jednodussi cestou - kontroluje se expiration date tokenu (typicky mivaji zivotnost 60 minut) a pokud vyprse (nebo se blizi vyprseni), tak se vyzada novy.
Pokud by to dal delalo problemy, dal by se jeste kontrolovat error response a podle te to refreshovat, ale uz by to bylo asi o neco slozitejsi.

PST-689 Refresh token

---

Dockerfile
azure-pipelines.yml
docker-compose.yml
libs/settle/.gitignore
libs/settle/LICENSE
libs/settle/README.md
libs/settle/azure-pipelines.tests.yml
libs/settle/composer.json
libs/settle/infection.json.dist
libs/settle/phpcs.xml
libs/settle/phpstan.neon
libs/settle/phpunit.xml.dist
libs/settle/src/Comparator/ComparatorInterface.php
libs/settle/src/Comparator/InArray.php
libs/settle/src/Comparator/IsSame.php
libs/settle/src/Comparator/IsTrue.php
libs/settle/src/Settle.php
libs/settle/src/SettleFactory.php
libs/settle/tests/Comparator/InArrayTest.php
libs/settle/tests/Comparator/IsSameTest.php
libs/settle/tests/Comparator/IsTrueTest.php
libs/settle/tests/SettleFactoryTest.php
libs/settle/tests/SettleTest.php
libs/settle/tests/bootstrap.php

https://keboola.atlassian.net/browse/PST-769

Add Settle library

---

libs/output-mapping/src/Writer/Helper/PrimaryKeyHelper.php
libs/output-mapping/src/Writer/Helper/TypedColumnsHelper.php
libs/output-mapping/src/Writer/TableWriter.php
libs/output-mapping/tests/Writer/Helper/PrimaryKeyHelperTest.php
libs/output-mapping/tests/Writer/Helper/TypedColumnsHelperTest.php
libs/output-mapping/tests/Writer/TableDefinitionTest.php

Fixes: https://keboola.atlassian.net/browse/PST-745

Output mapping - add missing columns to typed table

---

libs/output-mapping/src/Writer/Helper/ConfigurationMerger.php
libs/output-mapping/tests/Writer/Helper/ConfigurationMergerTest.php
libs/output-mapping/tests/Writer/Helper/PrimaryKeyHelperTest.php

Fixes https://keboola.atlassian.net/browse/PST-734

OM testModifyPrimaryKeyChangeToEmpty

---

libs/output-mapping/composer.json
libs/output-mapping/src/DeferredTasks/FailedLoadTableDecider.php
libs/output-mapping/src/DeferredTasks/LoadTableQueue.php
libs/output-mapping/src/DeferredTasks/LoadTableTaskInterface.php
libs/output-mapping/src/DeferredTasks/TableWriter/AbstractLoadTableTask.php
libs/output-mapping/src/Writer/TableWriter.php
libs/output-mapping/tests/DeferredTasks/CreateAndLoadTableTaskTest.php
libs/output-mapping/tests/DeferredTasks/FailedLoadTableDeciderTest.php
libs/output-mapping/tests/DeferredTasks/LoadTableQueueTest.php
libs/output-mapping/tests/DeferredTasks/LoadTableTaskTest.php
libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php

https://keboola.atlassian.net/browse/PST-764
depends on https://github.com/keboola/platform-libraries/pull/76

Drop empty table after failed load

---

libs/input-mapping/src/File/Strategy/AbstractStrategy.php
libs/input-mapping/tests/Functional/DownloadFilesTest.php

https://keboola.atlassian.net/browse/PST-736

Fix filename in log

---

libs/k8s-client/tests/stubs/K8s.stub

https://keboola.atlassian.net/browse/PST-820
Pouzite tu https://github.com/keboola/job-queue-daemon/pull/404
Rozsireni stubu o veci, na ktere jsme ted narazil nove na daemonovi.

Extend K8S stub

---

libs/input-mapping/tests/Functional/DownloadTablesSynapseTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceAbsTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceSynapseTest.php
libs/output-mapping/src/Writer/Helper/TableColumnsHelper.php
libs/output-mapping/tests/Writer/Helper/TableColumnsHelperTest.php

https://keboola.atlassian.net/browse/PST-852
https://keboola.slack.com/archives/CQB468K63/p1682322553053839

fix adding columns in weird cases

---

libs/output-mapping/src/DeferredTasks/LoadTableQueue.php
libs/output-mapping/tests/DeferredTasks/LoadTableQueueTest.php

https://keboola.atlassian.net/browse/PST-866

delete table after failed upload also for shared buckets

---

libs/input-mapping/src/File/Strategy/ABSWorkspace.php
libs/input-mapping/tests/AbstractTestCase.php
libs/input-mapping/tests/Functional/DownloadFilesAbsWorkspaceTest.php
libs/output-mapping/src/DeferredTasks/TableWriter/LoadTableTask.php
libs/output-mapping/tests/AbstractTestCase.php
libs/staging-provider/src/Provider/WorkspaceStagingProvider.php
libs/staging-provider/src/WorkspaceProviderFactory/ExistingDatabaseWorkspaceProviderFactory.php
libs/staging-provider/src/WorkspaceProviderFactory/ExistingFilesystemWorkspaceProviderFactory.php
libs/staging-provider/tests/WorkspaceProviderFactory/ExistingDatabaseWorkspaceProviderFactoryTest.php
libs/staging-provider/tests/WorkspaceProviderFactory/ExistingFilesystemWorkspaceProviderFactoryTest.php

https://keboola.atlassian.net/browse/SOX-71

Fix tests after SAPI client updates type hints

---

libs/input-mapping/src/File/Strategy/ABSWorkspace.php
libs/input-mapping/tests/AbstractTestCase.php
libs/input-mapping/tests/Functional/DownloadFilesAbsWorkspaceTest.php
libs/output-mapping/tests/AbstractTestCase.php
libs/staging-provider/src/Provider/WorkspaceStagingProvider.php
libs/staging-provider/src/WorkspaceProviderFactory/ExistingDatabaseWorkspaceProviderFactory.php
libs/staging-provider/src/WorkspaceProviderFactory/ExistingFilesystemWorkspaceProviderFactory.php

Testy zacaly z niceho nic failovat. Predpokaldam ze to souvisi s nedavnym releasem SAPI klienta.

Fix IM/OM after SAPI client updates type hints

---

libs/api-bundle/config/services.yaml
libs/api-bundle/provisioning/production/.gitignore
libs/api-bundle/provisioning/production/aws/.terraform.lock.hcl
libs/api-bundle/provisioning/production/aws/aws.tf
libs/api-bundle/provisioning/production/aws/deploy.sh
libs/api-bundle/provisioning/production/aws/k8s_ingress.tf
libs/api-bundle/provisioning/production/aws/kubernetes.tf
libs/api-bundle/provisioning/production/aws/main.tf
libs/api-bundle/provisioning/production/azure/.terraform.lock.hcl
libs/api-bundle/provisioning/production/azure/azure.tf
libs/api-bundle/provisioning/production/azure/deploy.sh
libs/api-bundle/provisioning/production/azure/k8s_ingress.tf
libs/api-bundle/provisioning/production/azure/main.tf
libs/api-bundle/provisioning/production/common/kubernetes.tf
libs/api-bundle/provisioning/production/common/kubernetes_deployment_api.tf
libs/api-bundle/provisioning/production/common/kubernetes_job_databaseInit.tf
libs/api-bundle/provisioning/production/common/kubernetes_job_databaseMigration.tf
libs/api-bundle/provisioning/production/common/main.tf
libs/api-bundle/provisioning/production/common/variables.tf
libs/api-bundle/src/Attribute/ManageApiTokenAuth.php
libs/api-bundle/src/Attribute/StorageApiTokenAuth.php
libs/api-bundle/src/DependencyInjection/KeboolaApiExtension.php
libs/api-bundle/src/Security/ManageApiToken/ManageApiClientFactory.php
libs/api-bundle/src/Security/ManageApiToken/ManageApiToken.php
libs/api-bundle/src/Security/ManageApiToken/ManageApiTokenAuthenticator.php
libs/api-bundle/src/Security/StorageApiToken/StorageApiTokenAuthenticator.php
libs/api-bundle/tests/Security/AuthenticatedController.php

https://keboola.atlassian.net/browse/SOX-48
* fix StorageToken auth initialization
* make features optional, allow `#[StorageTokenAuth]`
* unify token naming

SOX-48 Api-bundle tuning

---

libs/api-bundle/composer.json
libs/api-bundle/src/Resources/config/security.php
libs/api-bundle/src/Security/StorageApiToken/StorageApiToken.php
libs/api-bundle/tests/Security/StorageApiToken/StorageApiTokenTest.php

https://keboola.atlassian.net/browse/SOX-50
Aby slo token poslat rovnou do permission checkeru

[api-bundle] Implement PermissionChecker::StorageApiTokenInterface

---

libs/permission-checker/composer.json
libs/permission-checker/src/Check/Vault/CanModifyVariable.php
libs/permission-checker/tests/Check/JobQueue/CanRunJobTest.php
libs/permission-checker/tests/Check/Notification/CanModifySubscriptionsTest.php
libs/permission-checker/tests/Check/Vault/CanModifyVariableTest.php

https://keboola.atlassian.net/browse/SOX-50

[permission-checker] SOX-50 Vault check

---

azure-pipelines.tags.yml

Jde o tuhle pipeline https://dev.azure.com/keboola-dev/Platform%20Libraries/_build/results?buildId=35082&view=results

fix permission checker releases

---

libs/input-mapping/composer.json
libs/input-mapping/src/Helper/FakeDevStorageTableRewriteHelper.php
libs/input-mapping/src/Helper/RealDevStorageTableRewriteHelper.php
libs/input-mapping/src/Helper/TableRewriteHelperFactory.php
libs/input-mapping/src/Helper/TableRewriteHelperInterface.php
libs/input-mapping/src/Reader.php
libs/input-mapping/src/Table/Options/InputTableOptions.php
libs/input-mapping/src/Table/Options/ReaderOptions.php
libs/input-mapping/src/Table/Strategy/AbstractDatabaseStrategy.php
libs/input-mapping/tests/Functional/DownloadTablesDefaultTest.php
libs/input-mapping/tests/Helper/FakeDevStorageTableRewriteHelperTest.php
libs/input-mapping/tests/Helper/RealDevStorageTableRewriteHelperTest.php
libs/input-mapping/tests/Helper/TableRewriteHelperFactoryTest.php
libs/input-mapping/tests/Table/Options/InputTableOptionsTest.php
libs/input-mapping/tests/Table/Options/ReaderOptionsTest.php
libs/output-mapping/src/Writer/FileWriter.php
libs/output-mapping/src/Writer/Table/TableConfigurationResolver.php
libs/output-mapping/tests/Writer/StorageApiFileWriterTest.php
libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php

https://keboola.atlassian.net/browse/SOX-139
Řeší i files i tables

Real dev storage on output mapping

---

libs/input-mapping/composer.json
libs/input-mapping/src/Helper/FakeDevStorageTableRewriteHelper.php
libs/input-mapping/src/Helper/RealDevStorageTableRewriteHelper.php
libs/input-mapping/src/Helper/TableRewriteHelperFactory.php
libs/input-mapping/src/Helper/TableRewriteHelperInterface.php
libs/input-mapping/src/Reader.php
libs/input-mapping/src/Table/Options/InputTableOptions.php
libs/input-mapping/src/Table/Options/ReaderOptions.php
libs/input-mapping/src/Table/Strategy/AbstractDatabaseStrategy.php
libs/input-mapping/tests/Functional/DownloadTablesDefaultTest.php
libs/input-mapping/tests/Helper/FakeDevStorageTableRewriteHelperTest.php
libs/input-mapping/tests/Helper/RealDevStorageTableRewriteHelperTest.php
libs/input-mapping/tests/Helper/TableRewriteHelperFactoryTest.php
libs/input-mapping/tests/Table/Options/InputTableOptionsTest.php
libs/input-mapping/tests/Table/Options/ReaderOptionsTest.php

https://keboola.atlassian.net/browse/SOX-138
Chybí tomu fallback na files, bude se řešit separátně

Branched table fallback for protected branch storage in IM

---

libs/api-bundle/src/Security/StorageApiToken/StorageApiToken.php
libs/api-bundle/tests/Security/StorageApiToken/StorageApiTokenTest.php
libs/permission-checker/src/Check/JobQueue/CanRunJob.php
libs/permission-checker/src/StorageApiToken.php
libs/permission-checker/src/StorageApiTokenInterface.php
libs/permission-checker/src/TokenPermission.php
libs/permission-checker/tests/Check/JobQueue/CanRunJobTest.php
libs/permission-checker/tests/Keboola/PermissionChecker/PermissionCheckerTest.php
libs/permission-checker/tests/StorageApiTokenTest.php

Fixes: https://keboola.atlassian.net/browse/SOX-233

Permisson checker - allow run for non-admin tokens having canRunJobs permission

---

libs/api-bundle/composer.json
libs/api-bundle/src/Security/StorageApiToken/StorageApiToken.php

Fixes: https://keboola.atlassian.net/browse/SOX-60

[api-bundle] use permission-checker 2.0

---

libs/input-mapping/phpstan.neon
libs/input-mapping/src/File/Options/InputFileOptions.php
libs/input-mapping/src/File/Options/InputFileOptionsList.php
libs/input-mapping/src/File/Options/RewrittenInputFileOptions.php
libs/input-mapping/src/File/Options/RewrittenInputFileOptionsList.php
libs/input-mapping/src/Helper/TagsRewriteHelper.php
libs/input-mapping/src/Reader.php
libs/input-mapping/tests/File/Options/InputFileOptionsListTest.php
libs/input-mapping/tests/File/Options/InputFileOptionsTest.php
libs/input-mapping/tests/File/Options/RewrittenInputFileOptionsListTest.php
libs/input-mapping/tests/File/Options/RewrittenInputFileOptionsTest.php
libs/input-mapping/tests/Functional/DownloadTablesRedshiftTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceRedshiftTest.php
libs/input-mapping/tests/Helper/TagsRewriteHelperTest.php
libs/input-mapping/tests/ReaderTest.php

https://keboola.atlassian.net/browse/SOX-234

Fallback to production in IM files step 1

---

libs/input-mapping/src/File/Options/RewrittenInputFileOptions.php
libs/input-mapping/src/File/Strategy/ABSWorkspace.php
libs/input-mapping/src/File/Strategy/AbstractStrategy.php
libs/input-mapping/src/File/Strategy/Local.php
libs/input-mapping/src/File/StrategyInterface.php
libs/input-mapping/src/Helper/BuildQueryFromConfigurationHelper.php
libs/input-mapping/src/Helper/FakeDevStorageTagsRewriteHelper.php
libs/input-mapping/src/Helper/RealDevStorageTagsRewriteHelper.php
libs/input-mapping/src/Helper/TagsRewriteHelperFactory.php
libs/input-mapping/src/Helper/TagsRewriteHelperInterface.php
libs/input-mapping/src/Reader.php
libs/input-mapping/tests/File/Options/RewrittenInputFileOptionsListTest.php
libs/input-mapping/tests/File/Options/RewrittenInputFileOptionsTest.php
libs/input-mapping/tests/Functional/DownloadFilesBranchTest.php
libs/input-mapping/tests/Helper/FakeDevStorageTagsRewriteHelperTest.php
libs/input-mapping/tests/Helper/RealDevStorageTagsRewriteHelperTest.php
libs/input-mapping/tests/Helper/TagsRewriteHelperFactoryTest.php

https://keboola.atlassian.net/browse/SOX-234
Přehlídka velmi špatnýho kódu a ještě horších interfaců, ale snažil jsem se dělat co nejmíň změn
depends on https://github.com/keboola/platform-libraries/pull/132

fallback to main branch in real dev storage file input mapping

---

libs/output-mapping/src/Writer/FileWriter.php
libs/output-mapping/tests/Writer/StorageApiFileWriterTest.php

follow up to https://github.com/keboola/platform-libraries/pull/135
handles the BC break created in IM getFiles method

fix handling of processed tags in OM

---

libs/api-bundle/src/ServiceClient.php
libs/api-bundle/tests/ServiceClientTest.php

https://keboola.atlassian.net/browse/SOX-133
Pridani Vault service

[api-bundle] Add Vault service URL

---

libs/staging-provider/composer.json

Part of https://keboola.atlassian.net/browse/SOX-297
Storage API client od verze 4.11.1 interně řeší získávání hesla při zakládání workspace pomocí async callu

[staging-provider] composer: min sapi client version 4.11.1

---

libs/input-mapping/composer.json
libs/output-mapping/composer.json

Part of: https://keboola.atlassian.net/browse/SOX-297
V testech zakládáme workspaces, tak ať se pak v budoucnu nedivíme

[im/om] composer: min sapi client version 4.11.1

---

libs/input-mapping/composer.json
libs/input-mapping/src/File/Strategy/ABSWorkspace.php
libs/input-mapping/src/File/Strategy/AbstractStrategy.php
libs/input-mapping/src/File/Strategy/Local.php
libs/input-mapping/src/File/StrategyInterface.php
libs/input-mapping/src/Helper/FakeDevStorageTableRewriteHelper.php
libs/input-mapping/src/Helper/FakeDevStorageTagsRewriteHelper.php
libs/input-mapping/src/Helper/RealDevStorageTableRewriteHelper.php
libs/input-mapping/src/Helper/RealDevStorageTagsRewriteHelper.php
libs/input-mapping/tests/Functional/DownloadFilesBranchTest.php
libs/input-mapping/tests/Functional/DownloadTablesDefaultTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceSnowflakeTest.php
libs/input-mapping/tests/Helper/FakeDevStorageTableRewriteHelperTest.php
libs/input-mapping/tests/Helper/RealDevStorageTableRewriteHelperTest.php
libs/input-mapping/tests/Helper/RealDevStorageTagsRewriteHelperTest.php
libs/input-mapping/tests/Table/Strategy/BigQueryTest.php
libs/input-mapping/tests/Table/Strategy/ExasolTest.php
libs/input-mapping/tests/Table/Strategy/LocalStrategyTest.php
libs/input-mapping/tests/Table/Strategy/S3StrategyTest.php
libs/input-mapping/tests/Table/Strategy/TeradataTest.php
libs/output-mapping/composer.json
libs/staging-provider/composer.json

https://keboola.atlassian.net/browse/SOX-302

update client wrapper to 5.0

---

libs/configuration-variables-resolver/composer.json
libs/input-mapping/src/File/Options/RewrittenInputFileOptions.php
libs/input-mapping/tests/ReaderTest.php

https://keboola.atlassian.net/browse/SOX-332

Remove obsolete stuff

---

libs/input-mapping/composer.json
libs/output-mapping/composer.json
libs/staging-provider/composer.json

Fixes https://keboola.atlassian.net/browse/SOX-297

composer: storage-api-client min 14.11.2

---

libs/api-bundle/README.md

V README byl nejaky C&P bordel + chybelo info o tom, jak funguje automaticka konfigurace

[api-bundle] README cleanup

---

libs/input-mapping/src/Configuration/Table.php
libs/input-mapping/tests/Configuration/TableConfigurationTest.php

https://keboola.atlassian.net/browse/SOX-339

add new source_branch_id parameter 

---

libs/input-mapping/src/Helper/RealDevStorageTableRewriteHelper.php
libs/input-mapping/src/Table/Options/InputTableOptions.php
libs/input-mapping/src/Table/Options/RewrittenInputTableOptions.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceSnowflakeTest.php
libs/input-mapping/tests/Helper/FakeDevStorageTableRewriteHelperTest.php
libs/input-mapping/tests/Helper/RealDevStorageTableRewriteHelperTest.php
libs/input-mapping/tests/Table/Options/InputTableOptionsTest.php
libs/input-mapping/tests/Table/Options/RewrittenInputTableOptionsTest.php

… to InputTableOptions
Fixes: https://keboola.atlassian.net/browse/SOX-333
Multi branch IM pro SOX projekt

IM - source_branch_id

---

libs/configuration-variables-resolver/src/ResolveResults.php
libs/configuration-variables-resolver/src/VariablesRenderer/MustacheRenderer.php
libs/configuration-variables-resolver/src/VariablesRenderer/MustacheVariablesContext.php
libs/configuration-variables-resolver/src/VariablesRenderer/RegexRenderer.php
libs/configuration-variables-resolver/src/VariablesRenderer/RenderResults.php
libs/configuration-variables-resolver/src/VariablesResolver.php
libs/configuration-variables-resolver/src/VariablesResolver/ConfigurationVariablesResolver.php
libs/configuration-variables-resolver/tests/VariableResolverTest.php
libs/configuration-variables-resolver/tests/VariablesRenderer/MustacheRendererTest.php
libs/configuration-variables-resolver/tests/VariablesRenderer/MustacheVariablesContextTest.php
libs/configuration-variables-resolver/tests/VariablesRenderer/RegexRendererTest.php
libs/configuration-variables-resolver/tests/VariablesResolver/ConfigurationVariablesResolverTest.php
libs/configuration-variables-resolver/tests/VariablesResolver/VaultVariablesResolverTest.php
libs/configuration-variables-resolver/tests/VariablesResolverFunctionalTest.php
libs/configuration-variables-resolver/tests/VariablesResolverTest.php

Part of https://keboola.atlassian.net/browse/SOX-391

Variable Resolver - Render + Resolve Results to store variable values

---

libs/messenger-bundle/provisioning/ci/.terraform.lock.hcl
libs/messenger-bundle/provisioning/ci/README.md
libs/messenger-bundle/provisioning/ci/aws.tf
libs/messenger-bundle/provisioning/ci/aws_queue.tf
libs/messenger-bundle/provisioning/ci/azure.tf
libs/messenger-bundle/provisioning/ci/azure_queue.tf
libs/messenger-bundle/provisioning/ci/env-scripts/extract-variables-aws.sh
libs/messenger-bundle/provisioning/ci/env-scripts/extract-variables-azure.sh
libs/messenger-bundle/provisioning/ci/env-scripts/extract-variables-common.sh
libs/messenger-bundle/provisioning/ci/env-scripts/functions.sh
libs/messenger-bundle/provisioning/ci/main.tf
libs/messenger-bundle/provisioning/ci/pipelines-scripts/terraform-init.sh
libs/messenger-bundle/provisioning/ci/pipelines-scripts/terraform-install.sh
libs/messenger-bundle/provisioning/ci/prepare-aws-resources.sh
libs/messenger-bundle/provisioning/ci/resources/aws.yaml
libs/messenger-bundle/provisioning/ci/s3.tfbackend
libs/messenger-bundle/provisioning/ci/update-env.sh

https://keboola.atlassian.net/browse/SOX-423
CI provisioning pro messenger bundle - user a fronta na Azure a AWS
CI je ocekavane, ze je tu cervene. Mergovat budu pak cely SOX-423 v ramci https://github.com/keboola/platform-libraries/pull/165

SOX-423 [messenger-bundle] CI provisioning

---

Dockerfile
libs/messenger-bundle/README.md
libs/messenger-bundle/azure-pipelines.tests.yml
libs/messenger-bundle/composer.json
libs/messenger-bundle/provisioning/ci/.terraform.lock.hcl
libs/messenger-bundle/provisioning/ci/env-scripts/extract-variables-gcp.sh
libs/messenger-bundle/provisioning/ci/gcp.tf
libs/messenger-bundle/provisioning/ci/gcp_queue.tf
libs/messenger-bundle/provisioning/ci/main.tf
libs/messenger-bundle/provisioning/ci/update-env.sh
libs/messenger-bundle/provisioning/local/.terraform.lock.hcl
libs/messenger-bundle/provisioning/local/env-scripts/extract-variables-gcp.sh
libs/messenger-bundle/provisioning/local/env-scripts/functions.sh
libs/messenger-bundle/provisioning/local/gcp.tf
libs/messenger-bundle/provisioning/local/gcp_queue.tf
libs/messenger-bundle/provisioning/local/main.tf
libs/messenger-bundle/provisioning/local/update-env.sh
libs/messenger-bundle/src/ConnectionEvent/Serializer/GooglePubSubSerializer.php
libs/messenger-bundle/src/DependencyInjection/KeboolaMessengerExtension.php
libs/messenger-bundle/src/Resources/config/messenger.php
libs/messenger-bundle/tests/ConnectionEvent/GooglePubSubConsumptionTest.php
libs/messenger-bundle/tests/ConnectionEvent/Serializer/GooglePubSubSerializerTest.php
libs/messenger-bundle/tests/KeboolaMessengerBundleTestingKernel.php

https://keboola.atlassian.net/browse/SOX-424
Pridani podpory pro Google Pub/Sub

SOX-424 [messenger-bundle] Pub/Sub support

---

libs/input-mapping/src/Configuration/File.php
libs/input-mapping/src/File/Options/RewrittenInputFileOptions.php
libs/input-mapping/tests/Configuration/FileConfigurationTest.php
libs/input-mapping/tests/File/Options/RewrittenInputFileOptionsTest.php
libs/input-mapping/tests/Functional/DownloadFilesTest.php

Fixes: https://keboola.atlassian.net/browse/SOX-299

File ID filter in IM

---

azure-pipelines.tags.yml
azure-pipelines.yml
docker-compose.yml
libs/output-mapping/composer.json
libs/slicer/.gitignore
libs/slicer/LICENSE
libs/slicer/README.md
libs/slicer/azure-pipelines.tests.yml
libs/slicer/composer.json
libs/slicer/infection.json.dist
libs/slicer/phpcs.xml
libs/slicer/phpstan.neon
libs/slicer/phpunit.xml.dist
libs/slicer/src/Downloader.php
libs/slicer/src/MachineTypeResolver.php
libs/slicer/src/Slicer.php
libs/slicer/src/UrlResolver.php
libs/slicer/tests/DownloaderTest.php
libs/slicer/tests/MachineTypeResolverTest.php
libs/slicer/tests/SlicerTest.php
libs/slicer/tests/UrlResolverTest.php
libs/slicer/tests/bootstrap.php

https://keboola.atlassian.net/browse/GCP-452
replaces https://github.com/keboola/platform-libraries/pull/179

composer package for Slicer tool

---

libs/staging-provider/composer.json

Fixup pro https://github.com/keboola/platform-libraries/pull/187
Do OM se pridal slicer z monorepa, tak je to potreba strcit i sem. Jinak pada build

[staging-provider] composer: keboola/slicer

---

libs/slicer/tests/UrlResolverTest.php

Michal vydal novou verzi sliceru, tak trošku povolíme assert

fix slicer test

---

libs/input-mapping/src/Helper/LoadTypeDecider.php
libs/input-mapping/src/Table/Strategy/AbstractDatabaseStrategy.php
libs/input-mapping/tests/Helper/LoadTypeDeciderTest.php
libs/input-mapping/tests/Table/Strategy/BigQueryTest.php

changed falses to exceptions because there is no other way to load such tables 
https://keboola.atlassian.net/browse/GCP-439

update rules for loading as view with BigQuery

---

libs/output-mapping/src/Exception/SliceSkippedException.php
libs/output-mapping/src/Writer/Helper/FilesHelper.php
libs/output-mapping/src/Writer/Helper/SliceCommandBuilder.php
libs/output-mapping/src/Writer/Helper/SliceHelper.php
libs/output-mapping/tests/Writer/Helper/FilesHelperTest.php
libs/output-mapping/tests/Writer/Helper/SliceCommandBuilderTest.php
libs/output-mapping/tests/Writer/Helper/SliceHelperTest.php
libs/output-mapping/tests/Writer/Table/Strategy/AbsWorkspaceTableStrategyTest.php

Fixes: https://keboola.atlassian.net/browse/GCP-456
Nema zadny vliv na funkcnost. Zatim jen knihovny, pouziti se resi az v https://github.com/keboola/platform-libraries/pull/190

[output-mapping] SliceHelper

---

libs/output-mapping/azure-pipelines.tests.yml
libs/output-mapping/composer.json
libs/output-mapping/phpunit.xml.dist
libs/output-mapping/src/Writer/Table/MappingResolver/LocalMappingResolver.php
libs/output-mapping/src/Writer/Table/MappingResolver/MappingResolverInterface.php
libs/output-mapping/src/Writer/Table/MappingResolver/WorkspaceMappingResolver.php
libs/output-mapping/src/Writer/Table/Strategy/LocalTableStrategy.php
libs/output-mapping/src/Writer/Table/TableConfigurationResolver.php
libs/output-mapping/src/Writer/TableWriter.php
libs/output-mapping/tests/AbstractTestCase.php
libs/output-mapping/tests/Writer/Redshift/StorageApiSlicedWriterRedshiftTest.php
libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php
libs/output-mapping/tests/Writer/StorageApiSlicedWriterTest.php
libs/output-mapping/tests/Writer/Table/MappingResolver/LocalMappingResolverTest.php
libs/output-mapping/tests/Writer/Table/MappingResolver/WorkspaceMappingResolverTest.php

Part3 of https://keboola.atlassian.net/browse/GCP-456

[output-mapping] Enable SliceHelper under feature

---

libs/messenger-bundle/src/DependencyInjection/KeboolaMessengerExtension.php
libs/messenger-bundle/tests/DependencyInjection/KeboolaMessengerExtensionTest.php

https://keboola.atlassian.net/browse/GCP-491

GCP-491 Configure default requestTimeout for Pub/Sub client

---

libs/input-mapping/src/Helper/FakeDevStorageTagsRewriteHelper.php
libs/input-mapping/src/Helper/RealDevStorageTagsRewriteHelper.php
libs/input-mapping/tests/Helper/RealDevStorageTagsRewriteHelperTest.php

https://keboola.atlassian.net/browse/SOX-299

Fix file_ids option rewritting

---

libs/output-mapping/phpunit.xml.dist
libs/output-mapping/src/Writer/Helper/SliceHelper.php
libs/output-mapping/tests/Writer/Helper/SliceHelperTest.php
libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php
libs/output-mapping/tests/Writer/StorageApiSlicedWriterTest.php

Fixes: https://keboola.atlassian.net/browse/GCP-457

[output-mapping] SliceHelper allow sliced source

---

libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php

Fixup jednoho testu z https://github.com/keboola/platform-libraries/pull/195

[output-mapping] testWriteAlwaysFlag fixup

---

libs/messenger-bundle/src/DependencyInjection/KeboolaMessengerExtension.php
libs/messenger-bundle/tests/DependencyInjection/KeboolaMessengerExtensionTest.php

https://keboola.atlassian.net/browse/GCP-491
Sjednoceni konfigurace timeoutu s ostatnima GCP klientama.

[messenger-bundle] GCP-491 Unify default requestTimeout

---

libs/output-mapping/tests/Writer/Helper/SliceHelperTest.php
libs/slicer/src/UrlResolver.php

Update sliceru na verzi ktera si poradi s tim, kdyz je na vstupu neslicovany soubor a manifest s prazdnyma columns

Erik gcp 518 slicer2.2

---

libs/output-mapping/src/Writer/Helper/SliceCommandBuilder.php
libs/output-mapping/tests/Writer/Helper/SliceCommandBuilderTest.php
libs/slicer/.gitignore
libs/slicer/composer.json
libs/slicer/src/Downloader.php
libs/slicer/src/Slicer.php
libs/slicer/tests/DownloaderTest.php
libs/slicer/tests/SlicerTest.php

Fixes: https://keboola.atlassian.net/browse/GCP-532
Nakonec to bude muset byt takhle, ze se to stahne do bin slozky primo u te slicer php knihovny. Ta globalni promenna na composer bin dir neni definovana vsude 🤦

Slicer binary install

---

libs/input-mapping/composer.json
libs/input-mapping/tests/AbstractTestCase.php
libs/input-mapping/tests/Functional/DownloadFilesAdaptiveBranchTest.php
libs/input-mapping/tests/Functional/DownloadFilesBranchTest.php
libs/input-mapping/tests/Functional/DownloadFilesTest.php
libs/input-mapping/tests/Functional/DownloadTablesABSDefaultTest.php
libs/input-mapping/tests/Functional/DownloadTablesDefaultTest.php
libs/input-mapping/tests/Functional/DownloadTablesS3DefaultTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceAbsTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceBigQueryTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceRedshiftTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceSnowflakeTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceSynapseTest.php
libs/input-mapping/tests/Helper/FakeDevStorageTableRewriteHelperTest.php
libs/input-mapping/tests/Helper/FakeDevStorageTagsRewriteHelperTest.php
libs/input-mapping/tests/Helper/RealDevStorageTableRewriteHelperTest.php
libs/input-mapping/tests/Helper/RealDevStorageTagsRewriteHelperTest.php
libs/output-mapping/tests/AbstractTestCase.php
libs/output-mapping/tests/DeferredTasks/FailedLoadTableDeciderTest.php
libs/output-mapping/tests/Writer/File/Strategy/ABSWorkspaceTest.php
libs/output-mapping/tests/Writer/File/Strategy/LocalTest.php
libs/output-mapping/tests/Writer/Helper/PrimaryKeyHelperTest.php
libs/output-mapping/tests/Writer/Helper/SliceHelperTest.php
libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php
libs/output-mapping/tests/Writer/Table/MappingResolver/LocalMappingResolverTest.php

Po mergi https://github.com/keboola/platform-libraries/pull/211 začaly padat libky input/output-mapping

Fix test logger input/output-mapping

---

libs/staging-provider/src/Staging/Workspace/BigQueryWorkspaceStaging.php
libs/staging-provider/tests/Staging/Workspace/BigQueryWorkspaceStagingTest.php

JIRA: https://keboola.atlassian.net/browse/GMT-139

Add region to BQ staging provider

---

libs/api-bundle/config/services.yaml
libs/api-bundle/phpunit.xml.dist
libs/api-bundle/src/DependencyInjection/Configuration.php
libs/api-bundle/src/DependencyInjection/KeboolaApiExtension.php
libs/api-bundle/src/Security/ManageApiToken/ManageApiClientFactory.php

(due to https://keboola.atlassian.net/browse/PST-1181)

PST-1181: ManageApiClientFactory constr. accepts instance of ServiceClient instead of storageApiUrl

---

azure-pipelines.tags.yml
azure-pipelines.yml

Jeste tohle chybelo v tags pipeline

ci (azure-pipelines.tags): missin sandboxes-service-api-client

---

libs/sandboxes-service-api-client/src/Sandboxes/SandboxesApiClient.php
libs/sandboxes-service-api-client/tests/Sandboxes/SandboxesApiClientTest.php

https://keboola.atlassian.net/browse/PST-1280

PST-1280: feat (sandboxes-service-api-client): deleteSandbox method

---

azure-pipelines.tags.yml
azure-pipelines.yml
docker-compose.yml
libs/service-client/.gitignore
libs/service-client/LICENSE
libs/service-client/README.md
libs/service-client/azure-pipelines.tests.yml
libs/service-client/composer.json
libs/service-client/infection.json.dist
libs/service-client/phpcs.xml
libs/service-client/phpstan.neon
libs/service-client/phpunit.xml.dist
libs/service-client/src/Service.php
libs/service-client/src/ServiceClient.php
libs/service-client/src/ServiceDnsType.php
libs/service-client/tests/ServiceClientTest.php
libs/service-client/tests/ServiceTest.php
libs/service-client/tests/bootstrap.php

https://keboolaglobal.slack.com/archives/C055HSMKX51/p1709188493228399
Needed for https://keboola.atlassian.net/browse/PST-1233
Initialize lib - C&P `ServiceClient` from `api-bundle`.
`api-bundle` will be switched to this lib once released.

[services-client] Init lib

---

docker-compose.yml
libs/k8s-client/composer.json

Part 3 https://keboola.atlassian.net/browse/PST-1257

k8s client - Update property-info to v6

---

libs/input-mapping/src/File/Options/InputFileOptions.php
libs/input-mapping/src/Table/Options/InputTableOptions.php
libs/input-mapping/src/Table/Result/MetadataItem.php
libs/output-mapping/tests/Writer/Helper/PrimaryKeyHelperTest.php
libs/output-mapping/tests/Writer/TableDefinitionTest.php
libs/settle/tests/SettleFactoryTest.php

build v mainu falinul https://github.com/keboola/platform-libraries/runs/22571053829 protoze se aktulizovaly pravidla pro phpcs
tohle fixuje errory

phpcs fixup

---

libs/api-bundle/src/Attribute/ManageApiTokenAuth.php
libs/api-bundle/src/Security/ManageApiToken/ManageApiToken.php
libs/api-bundle/src/Security/ManageApiToken/ManageApiTokenAuthenticator.php
libs/api-bundle/tests/Security/ManageApiToken/ManageApiTokenAuthenticatorTest.php
libs/api-bundle/tests/Security/ManageApiToken/ManageApiTokenTest.php

JIRA: https://keboola.atlassian.net/browse/PST-1551

[api-bundle] Add super admin authorization for manage token

---

azure-pipelines.yml
azure-pipelines/jobs/run-tests.yml
libs/k8s-client/README.md
libs/k8s-client/azure-pipelines.tests.yml
libs/messenger-bundle/README.md
libs/messenger-bundle/azure-pipelines.tests.yml
libs/permission-checker/README.md
libs/permission-checker/azure-pipelines.tests.yml
libs/staging-provider/README.md

Oprava rozbiteho CI po nedavnem updatu CI runner image

Replace docker-compose -> docker compose

---

libs/sandboxes-service-api-client/src/Sandboxes/SandboxesApiClient.php
libs/sandboxes-service-api-client/tests/Sandboxes/SandboxesApiClientTest.php

https://keboola.atlassian.net/browse/PST-1498

PST-1498: Add SandboxesApiClient::getSandbox()

---

libs/sandboxes-service-api-client/src/Sandboxes/SandboxesApiClient.php
libs/sandboxes-service-api-client/tests/Sandboxes/SandboxesApiClientTest.php

https://keboola.atlassian.net/browse/PST-1499

PST-1499: Add SandboxesApiClient::getCurrentProject() 

---

libs/api-bundle/composer.json
libs/api-bundle/src/RequestMapper/ArgumentResolver.php
libs/api-bundle/src/RequestMapper/Attribute/RequestMapperAttributeInterface.php
libs/api-bundle/src/RequestMapper/Attribute/RequestPayloadObject.php
libs/api-bundle/src/RequestMapper/Attribute/RequestQueryObject.php
libs/api-bundle/src/RequestMapper/DataMapper.php
libs/api-bundle/src/RequestMapper/Exception/InvalidPayloadException.php
libs/api-bundle/src/RequestMapper/Exception/RequestMapperException.php
libs/api-bundle/src/Resources/config/api_bundle.php
libs/api-bundle/tests/RequestMapper/ArgumentResolverTest.php
libs/api-bundle/tests/RequestMapper/DataMapperTest.php
libs/api-bundle/tests/RequestMapper/RequestData.php
libs/api-bundle/tests/RequestMapper/UnsupportedMapperAttribute.php

https://keboola.atlassian.net/browse/PST-1607
Request mapper pres Valinor.
Otestovano na `sandboxe-service` https://github.com/keboola/sandboxes-service/pull/174

PST-1607 [api-bundle] request mapper

---

libs/output-mapping/src/SourcesValidator/WorkspaceSourcesValidator.php
libs/output-mapping/src/Writer/Table/Strategy/AbstractWorkspaceTableStrategyNew.php
libs/output-mapping/tests/SourceValidator/WorkspaceSourcesValidatorTest.php
libs/output-mapping/tests/Writer/Workspace/WriterWorkspaceTest.php

https://keboolaglobal.slack.com/archives/C055HSMKX51/p1713535768722329?thread_ts=1713432623.070989&cid=C055HSMKX51

fix validation write_always in failed job in workspace

---

libs/output-mapping/src/Mapping/MappingFromProcessedConfiguration.php
libs/output-mapping/tests/Mapping/MappingFromProcessedConfigurationTest.php

https://keboolaglobal.slack.com/archives/C070PB10BTJ/p1713793423980959

fix delete_where_column has empty value

---

libs/output-mapping/src/Mapping/MappingFromRawConfigurationAndPhysicalDataWithManifest.php
libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php

https://keboolaglobal.slack.com/archives/C070B0YTB0D/p1713968297610239?thread_ts=1713959555.308269&cid=C070B0YTB0D

fix slicing tables

---

libs/configuration-variables-resolver/src/VariablesResolver.php
libs/configuration-variables-resolver/src/VariablesResolver/ConfigurationVariablesResolver.php
libs/configuration-variables-resolver/tests/SharedCodeResolverTest.php
libs/configuration-variables-resolver/tests/VariableResolverTest.php
libs/configuration-variables-resolver/tests/VariablesResolver/ConfigurationVariablesResolverTest.php
libs/configuration-variables-resolver/tests/VariablesResolverFunctionalTest.php
libs/configuration-variables-resolver/tests/VariablesResolverTest.php
libs/configuration-variables-resolver/tests/bootstrap.php

https://keboola.atlassian.net/browse/PST-1670

Hotfix: reduce variable replacement logging

---

libs/sandboxes-service-api-client/src/ApiClient.php
libs/sandboxes-service-api-client/src/Sandboxes/Legacy/Sandbox.php
libs/sandboxes-service-api-client/tests/Sandboxes/Legacy/SandboxTest.php

https://keboola.atlassian.net/browse/PST-1650

PST-1650: Extend Sandbox with componentId & configurationVersion props

---

libs/output-mapping/src/Configuration/Table/BaseConfiguration.php
libs/output-mapping/src/Configuration/Table/Configuration.php
libs/output-mapping/src/Configuration/Table/Manifest.php
libs/output-mapping/tests/Configuration/Table/BaseConfigurationTest.php
libs/output-mapping/tests/Configuration/Table/ConfigurationTest.php
libs/output-mapping/tests/Configuration/Table/ManifestTest.php
libs/output-mapping/tests/Configuration/TableTest.php
libs/output-mapping/tests/Writer/Table/TableConfigurationResolverTest.php

https://keboola.atlassian.net/browse/PST-1347

Native types manifest config

---

libs/output-mapping/src/OutputMappingSettings.php
libs/output-mapping/src/TableLoader.php
libs/output-mapping/src/Writer/TableWriter.php
libs/output-mapping/tests/OutputMappingSettingsTest.php
libs/output-mapping/tests/Writer/BaseWriterMetadataTest.php
libs/output-mapping/tests/Writer/Redshift/RedshiftWriterWorkspaceTest.php
libs/output-mapping/tests/Writer/Redshift/StorageApiLocalTableWriterRedshiftTest.php
libs/output-mapping/tests/Writer/Redshift/StorageApiSlicedWriterRedshiftTest.php
libs/output-mapping/tests/Writer/SnowflakeWriterMetadataTest.php
libs/output-mapping/tests/Writer/StorageApiHeadlessWriterTest.php
libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php
libs/output-mapping/tests/Writer/StorageApiSlicedWriterTest.php
libs/output-mapping/tests/Writer/TableDefinitionTest.php
libs/output-mapping/tests/Writer/Workspace/AbsWriterWorkspaceTest.php
libs/output-mapping/tests/Writer/Workspace/SynapseWriterWorkspaceTest.php
libs/output-mapping/tests/Writer/Workspace/WriterWorkspaceTest.php

https://keboola.atlassian.net/browse/PST-1360

Load Native Types feature in OM settings class (úklid bordelu)

---

libs/output-mapping/src/OutputMappingSettings.php
libs/output-mapping/src/Writer/TableWriter.php
libs/output-mapping/tests/OutputMappingSettingsTest.php
libs/output-mapping/tests/Writer/BaseWriterMetadataTest.php
libs/output-mapping/tests/Writer/Redshift/RedshiftWriterWorkspaceTest.php
libs/output-mapping/tests/Writer/Redshift/StorageApiLocalTableWriterRedshiftTest.php
libs/output-mapping/tests/Writer/Redshift/StorageApiSlicedWriterRedshiftTest.php
libs/output-mapping/tests/Writer/SnowflakeWriterMetadataTest.php
libs/output-mapping/tests/Writer/StorageApiHeadlessWriterTest.php
libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php
libs/output-mapping/tests/Writer/StorageApiSlicedWriterTest.php
libs/output-mapping/tests/Writer/TableDefinitionTest.php
libs/output-mapping/tests/Writer/Workspace/AbsWriterWorkspaceTest.php
libs/output-mapping/tests/Writer/Workspace/SynapseWriterWorkspaceTest.php
libs/output-mapping/tests/Writer/Workspace/WriterWorkspaceTest.php

https://keboola.atlassian.net/browse/PST-1359

[PST-1359] Pass DataTypesSupport to OM

---

libs/output-mapping/src/TableLoader.php
libs/output-mapping/src/Writer/Helper/SliceCommandBuilder.php
libs/output-mapping/src/Writer/Table/Strategy/AbstractWorkspaceTableStrategy.php
libs/output-mapping/src/Writer/Table/Strategy/LocalTableStrategy.php
libs/output-mapping/src/Writer/Table/StrategyInterface.php
libs/output-mapping/tests/Writer/Helper/SliceCommandBuilderTest.php
libs/output-mapping/tests/Writer/Table/Strategy/AbstractWorkspaceTableStrategyTestCase.php
libs/slicer/src/UrlResolver.php

https://keboola.atlassian.net/browse/PST-1361

[PST-1361] Update Slicer

---

libs/output-mapping/phpunit.xml.dist
libs/output-mapping/src/Exception/InvalidTableStructureException.php
libs/output-mapping/src/Storage/TableStructureValidator.php
libs/output-mapping/src/TableLoader.php
libs/output-mapping/tests/Storage/BucketInfoTest.php
libs/output-mapping/tests/Storage/TableStructureValidatorTest.php
libs/output-mapping/tests/Writer/TableDefinitionV2Test.php

https://keboola.atlassian.net/browse/PST-1366

[PST-1366] typed tables: validate schema columns configuration

---

libs/output-mapping/src/Storage/TableStructureValidator.php
libs/output-mapping/tests/Storage/TableStructureValidatorTest.php
libs/output-mapping/tests/Writer/TableDefinitionV2Test.php

https://keboola.atlassian.net/browse/PST-1367

[PST-1367] validate not typed tables

---

libs/output-mapping/src/Mapping/MappingFromConfigurationSchemaColumnDataType.php
libs/output-mapping/src/Storage/TableStructureValidator.php
libs/output-mapping/tests/Mapping/MappingFromConfigurationSchemaDataTypeTest.php
libs/output-mapping/tests/Mapping/MappingFromConfigurationSchemaTest.php

https://keboola.atlassian.net/browse/PST-1368

[PST-1368] Decide whether to use DataType

---

libs/output-mapping/phpstan.neon
libs/output-mapping/src/Storage/StoragePreparer.php
libs/output-mapping/src/TableLoader.php
libs/output-mapping/tests/Storage/StoragePreparerTest.php
libs/output-mapping/tests/Writer/TableDefinitionV2Test.php

řeší se tu 2 tasky:
https://keboola.atlassian.net/browse/PST-1371
https://keboola.atlassian.net/browse/PST-1372

[PST-1371] create and load data to table on NNTF

---

libs/output-mapping/tests/Configuration/Table/BaseConfigurationTest.php

https://keboola.atlassian.net/browse/PST-1389
chyběl jen jeden test - zbytek už byl hotový

test: schema and columns cannot be set together

---

libs/output-mapping/src/Writer/Helper/ConfigurationMerger.php
libs/output-mapping/tests/Writer/Helper/ConfigurationMergerTest.php

https://keboola.atlassian.net/browse/PST-1390

merge schema from manifest and configuration

---

libs/output-mapping/src/TableLoader.php
libs/output-mapping/src/Writer/Table/TableHintsConfigurationSchemaResolver.php
libs/output-mapping/tests/Writer/Table/TableHintsConfigurationSchemaResolverTest.php
libs/output-mapping/tests/Writer/TableDefinitionV2Test.php

https://keboola.atlassian.net/browse/PST-1392
https://keboola.atlassian.net/wiki/spaces/ENGG/pages/3099787265/PENDING+RFC-2023-016+Native+Data+types+Take+2#Non-authoritative-dataTypesSupport

convert data types to metadata for hints dataTypeSupport value

---

libs/output-mapping/src/Storage/TableStructureValidator.php
libs/output-mapping/tests/Storage/TableStructureValidatorTest.php
libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php

https://keboola.atlassian.net/browse/PST-1695
tento PR řeší jen test na reordering + drobný fix ve validaci tabulky
withoutHeaders nikde v kódu nepoužíváme a podporu pro ignoredLinesCount přidáme v dalším PR - https://keboola.atlassian.net/browse/PST-1393

[PST-1695] Test columns reordering

---

libs/output-mapping/src/Mapping/MappingFromProcessedConfiguration.php
libs/output-mapping/src/TableLoader.php
libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php

https://keboola.atlassian.net/browse/PST-1393

[PST-1393] Add has_header option

---

libs/output-mapping/src/Mapping/MappingFromConfigurationSchemaColumn.php
libs/output-mapping/src/Mapping/MappingFromProcessedConfiguration.php
libs/output-mapping/tests/Mapping/MappingFromConfigurationSchemaTest.php
libs/output-mapping/tests/Mapping/MappingFromProcessedConfigurationTest.php

https://keboola.atlassian.net/browse/PST-1394

[PST-1394] add table/column description to metadata array

---

libs/output-mapping/src/DeferredTasks/Metadata/ColumnMetadata.php
libs/output-mapping/src/DeferredTasks/Metadata/SchemaColumnMetadata.php
libs/output-mapping/src/Mapping/MappingFromConfigurationSchemaColumn.php
libs/output-mapping/src/Mapping/MappingFromProcessedConfiguration.php
libs/output-mapping/src/Writer/Table/MetadataSetter.php
libs/output-mapping/tests/DeferredTasks/Metadata/SchemaColumnMetadataTest.php
libs/output-mapping/tests/Mapping/MappingFromConfigurationSchemaTest.php
libs/output-mapping/tests/Mapping/MappingFromProcessedConfigurationTest.php
libs/output-mapping/tests/Writer/Table/MetadataSetterTest.php
libs/output-mapping/tests/Writer/TableDefinitionV2Test.php

https://keboola.atlassian.net/browse/PST-1395

[PST-1395] Convert new metadata format to accepted Storage API format

---

libs/output-mapping/src/Writer/Helper/ConfigurationMerger.php
libs/output-mapping/tests/Writer/Helper/ConfigurationMergerTest.php

narazil jsem na to při testování v docker-bundle

Fix config merger - is not set table metadata in manifest

---

libs/output-mapping/src/Storage/StoragePreparer.php
libs/output-mapping/src/Storage/TableChangesStore.php
libs/output-mapping/src/TableLoader.php
libs/output-mapping/tests/Storage/StoragePreparerTest.php
libs/output-mapping/tests/Storage/TableChangesStoreTest.php

Dodělávky pro https://github.com/keboola/platform-libraries/pull/284
https://keboola.atlassian.net/browse/PST-1460
https://keboola.atlassian.net/browse/PST-1462

table changes: add missing columns fixups

---

libs/output-mapping/src/Storage/StoragePreparer.php
libs/output-mapping/src/Storage/TableChangesStore.php
libs/output-mapping/src/Storage/TableStructureModifierFromSchema.php
libs/output-mapping/src/Storage/TableStructureValidator.php
libs/output-mapping/src/TableLoader.php
libs/output-mapping/tests/Storage/StoragePreparerTest.php
libs/output-mapping/tests/Storage/TableChangesStoreTest.php
libs/output-mapping/tests/Storage/TableStructureModifierFromSchemaTest.php
libs/output-mapping/tests/Storage/TableStructureValidatorTest.php
libs/output-mapping/tests/Writer/TableDefinitionV2Test.php

https://keboola.atlassian.net/browse/PST-1460
https://keboola.atlassian.net/browse/PST-1462

table changes: add missing columns

---

libs/input-mapping/src/Helper/BuildQueryFromConfigurationHelper.php
libs/input-mapping/tests/Helper/BuildQueryFromConfigurationHelperTest.php

https://keboola.atlassian.net/browse/PST-324

[input-mapping] Fix source tags validation

---

libs/output-mapping/src/Storage/TableStructureModifierFromSchema.php
libs/output-mapping/src/Storage/TableStructureValidator.php
libs/output-mapping/tests/Storage/BigqueryTableStructureModifierFromSchemaTest.php
libs/output-mapping/tests/Storage/TableStructureModifierFromSchemaTest.php
libs/output-mapping/tests/Storage/TableStructureValidatorTest.php

https://keboola.atlassian.net/browse/PST-1466

OM - change column attributes (length)

---

libs/output-mapping/src/Storage/TableStructureValidator.php
libs/output-mapping/tests/Storage/TableStructureValidatorTest.php

https://keboola.atlassian.net/browse/PST-1473
https://keboola.atlassian.net/browse/PST-1474

Applicated column aliases

---

libs/output-mapping/composer.json
libs/output-mapping/src/Configuration/Table/Webalizer.php
libs/output-mapping/src/DeferredTasks/Metadata/ColumnMetadata.php
libs/output-mapping/src/DeferredTasks/Metadata/SchemaColumnMetadata.php
libs/output-mapping/src/Storage/TableStructureModifier.php
libs/output-mapping/src/Storage/TableStructureValidator.php
libs/output-mapping/src/TableLoader.php
libs/output-mapping/src/Writer/Helper/RestrictedColumnsHelper.php
libs/output-mapping/src/Writer/Helper/TableColumnsHelper.php
libs/output-mapping/tests/Configuration/Table/WebalizerTest.php
libs/output-mapping/tests/DeferredTasks/Metadata/ColumnMetadataTest.php
libs/output-mapping/tests/DeferredTasks/Metadata/SchemaColumnMetadataTest.php
libs/output-mapping/tests/Storage/TableStructureValidatorTest.php
libs/output-mapping/tests/Writer/Helper/TableColumnsHelperTest.php
libs/output-mapping/tests/Writer/Workspace/AbsWriterWorkspaceTest.php

https://keboola.atlassian.net/browse/PST-1705

Webalize column names over SAPI client

---

libs/output-mapping/src/Storage/TableStructureValidator.php
libs/output-mapping/tests/Storage/TableStructureModifierFromSchemaTest.php
libs/output-mapping/tests/Storage/TableStructureValidatorTest.php

https://keboola.atlassian.net/browse/PST-1469

Untyped tables - modify Primary Keys

---

libs/output-mapping/tests/Storage/BigqueryTableStructureModifierFromSchemaTest.php

https://keboola.atlassian.net/browse/PST-1933

Tests Bigquery nullability

---

libs/output-mapping/phpunit.xml.dist
libs/output-mapping/src/TableLoader.php
libs/output-mapping/tests/TableLoaderTest.php

Fixes: https://keboola.atlassian.net/browse/PST-1907

output-mapping: TableLoader::createTable handles StorageApi exceptions

---

libs/output-mapping/src/Configuration/Table/Webalizer.php
libs/output-mapping/src/TableLoader.php
libs/output-mapping/tests/Configuration/Table/WebalizerTest.php

https://keboola.atlassian.net/browse/PST-1935

Logging webalized column names

---

libs/output-mapping/src/Configuration/Table/Webalizer.php
libs/output-mapping/tests/Configuration/Table/WebalizerTest.php

https://dev.azure.com/keboola-dev/job-runner/_build/results?buildId=48910&view=logs&j=a0262d59-11ad-53e5-b058-1f9c88250f9d&t=1a94094c-84d9-5c51-7be4-3cb51196ae05&l=163

Fix webalize int values

---

libs/output-mapping/composer.json
libs/output-mapping/src/Configuration/Table/Webalizer.php
libs/output-mapping/src/OutputMappingSettings.php
libs/output-mapping/src/TableLoader.php
libs/output-mapping/tests/Configuration/Table/WebalizerTest.php
libs/output-mapping/tests/OutputMappingSettingsTest.php

https://keboola.atlassian.net/browse/PST-1943

Use connection webalize only on feature

---

libs/output-mapping/src/Writer/Table/TableDefinition/BaseTypeTableDefinitionColumn.php
libs/output-mapping/tests/Writer/Table/TableDefinition/TableDefinitionColumnFactoryTest.php

https://keboola.atlassian.net/browse/PST-1948

Old Native Types - fix null basetype

---

libs/output-mapping/src/Mapping/MappingFromProcessedConfiguration.php
libs/output-mapping/src/Storage/TableStructureModifier.php
libs/output-mapping/src/Writer/Table/TableDefinition/TableDefinitionFactory.php
libs/output-mapping/tests/Mapping/MappingFromProcessedConfigurationTest.php
libs/output-mapping/tests/Storage/TableStructureModifierTest.php
libs/output-mapping/tests/Writer/Table/TableDefinition/TableDefinitionFactoryTest.php

Fixes: https://keboola.atlassian.net/browse/PST-1960
Mělo by to být pokryté testama

output-mapping: Fix for columns with numeric names

---

libs/output-mapping/src/Storage/TableStructureValidator.php
libs/output-mapping/tests/Storage/TableStructureModifierFromSchemaTest.php
libs/output-mapping/tests/Storage/TableStructureValidatorTest.php

https://keboola.atlassian.net/browse/PST-1953

Add new column to untyped table

---

libs/output-mapping/src/Configuration/Table/Webalizer.php
libs/output-mapping/tests/Configuration/Table/WebalizerTest.php

https://keboola.atlassian.net/browse/PST-1987

TYPO - webalize primary_key

---

libs/output-mapping/src/DeferredTasks/FailedLoadTableDecider.php
libs/output-mapping/tests/DeferredTasks/FailedLoadTableDeciderTest.php
libs/output-mapping/tests/DeferredTasks/LoadTableQueueTest.php
libs/output-mapping/tests/Writer/TableDefinitionV2Test.php

https://keboola.atlassian.net/browse/PST-1991

[PST-1991] typed table - drop empty table after failed load

---

libs/output-mapping/src/Configuration/Table/BaseConfiguration.php
libs/output-mapping/tests/Configuration/Table/BaseConfigurationTest.php

https://keboola.atlassian.net/browse/PST-1988

[PST-1988] convert default/length int/bool values to string

---

libs/output-mapping/src/Storage/TableStructureModifierFromSchema.php
libs/output-mapping/src/Storage/TableStructureValidator.php
libs/output-mapping/src/Writer/Table/TableDefinitionFromSchema/TableDefinitionFromSchemaColumn.php
libs/output-mapping/tests/Storage/BigqueryTableStructureModifierFromSchemaTest.php
libs/output-mapping/tests/Storage/TableStructureModifierFromSchemaTest.php
libs/output-mapping/tests/Storage/TableStructureValidatorTest.php
libs/output-mapping/tests/Writer/Table/TableDefinitionFromSchema/TableDefinitionFromSchemaColumnTest.php

https://keboola.atlassian.net/browse/PST-2000

[PST-2000] Default value ignored when adding/changing column

---

libs/output-mapping/src/Configuration/Table/BaseConfiguration.php
libs/output-mapping/tests/Configuration/Table/BaseConfigurationTest.php

https://keboola.atlassian.net/browse/PST-2036

Column Metadata - turn off normalize keys

---

libs/permission-checker/phpstan.neon
libs/permission-checker/src/Check/SandboxesService/CanManageApp.php
libs/permission-checker/src/StorageApiToken.php
libs/permission-checker/tests/Check/SandboxesService/CanManageAppTest.php
libs/permission-checker/tests/PermissionCheckerTest.php
libs/permission-checker/tests/StorageApiTokenTest.php

Potřeba pro https://github.com/keboola/sandboxes-service/pull/237
Check, jestli může user (token) přistupovat k appce, tzn. musí být ze stejného projektu.

[sandboxes-service]: Manage app check

---

libs/api-bundle/src/RequestMapper/ArgumentResolver.php
libs/api-bundle/src/RequestMapper/Attribute/RequestQueryObject.php
libs/api-bundle/src/RequestMapper/DataMapper.php
libs/api-bundle/tests/RequestMapper/ArgumentResolverTest.php
libs/api-bundle/tests/RequestMapper/DataMapperTest.php
libs/api-bundle/tests/RequestMapper/RequestData.php

https://github.com/keboola/sandboxes-service/pull/238#discussion_r1749617141

PST-1926 always use allowPermissiveTypes for mapper

---

libs/input-mapping/src/Table/Result.php
libs/input-mapping/src/Table/Result/Column.php
libs/input-mapping/src/Table/Result/Metrics.php
libs/input-mapping/src/Table/Result/TableInfo.php
libs/input-mapping/tests/Functional/DownloadTablesOutputTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceBigQueryTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceSnowflakeTest.php
libs/input-mapping/tests/Table/Result/ColumnTest.php
libs/input-mapping/tests/Table/Result/MetricsTest.php
libs/input-mapping/tests/Table/Result/TableInfoTest.php
libs/input-mapping/tests/bootstrap.php

https://keboola.atlassian.net/browse/PST-777
Umozni zjednodusit implementaci exportu Resultu v https://github.com/keboola/job-queue/pull/268
Nevim jestli za tema generatorama byla nejaka hlubsi myslenka, ale minimalne ve stavajici implementaci tech class nedavaji smysl, protoze tam vsechny ty data jsou uz stejne natazeny v pameti. Jen to je teda BC break na API, takze to bude muset byt major release :roll_eyes:

PST-777 Make Result getters return regular arrays

---

libs/input-mapping/src/Configuration/Table.php
libs/input-mapping/tests/Configuration/TableConfigurationTest.php

Revert revertu pro přidání validace https://keboola.atlassian.net/browse/PST-525, protože už jsou konf upravené.

Validation of where_(column|values) field

---

libs/staging-provider/src/Provider/AbstractWorkspaceProvider.php
libs/staging-provider/tests/Provider/ExistingWorkspaceStagingProviderTest.php

Part of https://keboola.atlassian.net/browse/KAB-312
V https://github.com/keboola/platform-libraries/pull/315 jsem sice přidal property backend k `StorageApiWorkspace`. Ale zapomněl jsem k ní přidat getter

add getBackendType method

---

libs/output-mapping/src/Writer/Table/TableDefinition/TableDefinitionColumnFactory.php
libs/output-mapping/tests/Writer/Table/TableDefinition/TableDefinitionColumnFactoryTest.php

Reverts: https://keboola.atlassian.net/browse/PST-2051
Reverts keboola/platform-libraries#320

Revert "[output-mapping] TableDefinitionColumnFactory without NATIVE_BACKEND_…"

---

libs/sandboxes-service-api-client/src/Sandboxes/Legacy/Sandbox.php
libs/sandboxes-service-api-client/tests/Sandboxes/Legacy/SandboxTest.php

https://keboola.atlassian.net/browse/PST-2111
Pridani podpory pro `autoSuspendAfterSeconds`.

PST-2111 Add support for autoSuspendAfterSeconds

---

libs/output-mapping/tests/Storage/TableStructureModifierTest.php
libs/output-mapping/tests/Writer/StorageApiLocalTableWriterTest.php
libs/output-mapping/tests/Writer/TableDefinitionV2Test.php

https://keboola.atlassian.net/browse/PST-1844
\+ pofixoval jsem basetypes který se změnily na connection

test: long column name

---

libs/output-mapping/src/Storage/StoragePreparer.php
libs/output-mapping/tests/Storage/BigqueryStoragePreparerTest.php
libs/output-mapping/tests/Writer/TableDefinitionV2Test.php

https://keboola.atlassian.net/browse/PST-2197
pokud není schema tak není naplněný `tableChangeStore` a pak došlo k tomu že na `new_native_types` fičuře a legacy manifestu nedocházelo ke změnám na typovaných tabulkách pokud nějaký byly

NNT: update PKs with feature and legacy manifest

---

libs/k8s-client/composer.json
libs/k8s-client/provisioning/ci/aws_kubernetes.tf
libs/k8s-client/provisioning/ci/azure.tf
libs/k8s-client/provisioning/ci/azure_kubernetes.tf
libs/k8s-client/provisioning/local/aws.tf
libs/k8s-client/provisioning/local/azure.tf
libs/k8s-client/provisioning/local/kubernetes/main.tf
libs/k8s-client/provisioning/local/main.tf
libs/k8s-client/tests/ApiClient/PodsApiClientFunctionalTest.php

Part of https://keboola.atlassian.net/browse/PST-2226
Přidání testů na readLog v pods clientovi

 composer update kubernetes/php-runtime

---

libs/output-mapping/src/Writer/Helper/ConfigurationMerger.php
libs/output-mapping/tests/Writer/Helper/ConfigurationMergerTest.php
libs/output-mapping/tests/Writer/TableDefinitionV2Test.php

https://keboola.atlassian.net/browse/PST-2247

merge new manifest with legacy primary keys in configuration

---

libs/staging-provider/src/Provider/Configuration/NetworkPolicy.php
libs/staging-provider/src/Provider/Configuration/WorkspaceBackendConfig.php
libs/staging-provider/src/Provider/NewWorkspaceStagingProvider.php
libs/staging-provider/tests/CombinedProviderInitializerTest.php
libs/staging-provider/tests/InputProviderInitializerTest.php
libs/staging-provider/tests/OutputProviderInitializerTest.php
libs/staging-provider/tests/Provider/Configuration/WorkspaceBackendConfigTest.php
libs/staging-provider/tests/Provider/NewWorkspaceStagingProviderTest.php

https://keboola.atlassian.net/browse/PST-2086

createWorkspace: add network-policy

---

libs/output-mapping/src/Storage/TableStructureModifierFromSchema.php
libs/output-mapping/tests/Storage/TableStructureModifierFromSchemaTest.php

https://keboola.atlassian.net/browse/PST-2296

Don't change length if hasn't been changed

---

libs/input-mapping/azure-pipelines.tests.yml

Testy nad Synapse uz nespoustime

Disable synapse tests

---

libs/output-mapping/src/LoadTableTaskCreator.php
libs/output-mapping/src/TableLoader.php
libs/output-mapping/tests/LoadTableTaskCreatorTest.php

https://keboola.atlassian.net/browse/PST-1822

Add LoadTableTaskCreator

---

libs/doctrine-retry-bundle/composer.json

Potřebuju v ai-service updatnout symfony, tohle je poslední libka.

[doctrine-retry-bundle] Allow Symfony 7

---

libs/logging-bundle/composer.json

Tak po rebasu v ai-service tam ještě přibylo tohle...

[logging-bundle] allow Symfony 7

---

libs/output-mapping/src/Mapping/MappingFromConfigurationSchemaColumnDataType.php
libs/output-mapping/src/Writer/Table/TableDefinitionFromSchema/TableDefinitionFromSchemaColumn.php
libs/output-mapping/tests/Mapping/MappingFromConfigurationSchemaDataTypeTest.php
libs/output-mapping/tests/Writer/TableDefinitionV2BigQueryTest.php

https://keboola.atlassian.net/browse/PST-2387

check if column datatype backend exists

---

libs/output-mapping/src/Storage/TableDataModifier.php
libs/output-mapping/tests/Storage/TableDataModifierTest.php

https://keboola.atlassian.net/browse/PST-2369

Handling exceptions as UserError in TableDataModifier

---

libs/output-mapping/src/OutputMappingSettings.php
libs/output-mapping/tests/OutputMappingSettingsTest.php

https://keboola.atlassian.net/browse/PST-2394

[output-mapping] Disable native-types feature if new-native-types is set

---

libs/input-mapping/azure-pipelines.tests.yml
libs/input-mapping/composer.json
libs/input-mapping/tests/AbstractTestCase.php
libs/input-mapping/tests/Functional/DownloadFilesAdaptiveBranchTest.php
libs/input-mapping/tests/Functional/DownloadFilesAdaptiveTest.php
libs/input-mapping/tests/Functional/DownloadFilesBranchTest.php
libs/input-mapping/tests/Functional/DownloadFilesTest.php
libs/input-mapping/tests/Functional/DownloadFilesTestAbstract.php
libs/input-mapping/tests/Functional/DownloadTablesABSDefaultTest.php
libs/input-mapping/tests/Functional/DownloadTablesAdaptiveTest.php
libs/input-mapping/tests/Functional/DownloadTablesBigQueryTest.php
libs/input-mapping/tests/Functional/DownloadTablesDefaultTest.php
libs/input-mapping/tests/Functional/DownloadTablesOutputTest.php
libs/input-mapping/tests/Functional/DownloadTablesRedshiftTest.php
libs/input-mapping/tests/Functional/DownloadTablesS3DefaultTest.php
libs/input-mapping/tests/Functional/DownloadTablesSynapseTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceAbsTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceBigQueryTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceRedshiftTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceSnowflakeAdaptiveTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceSnowflakeTest.php
libs/input-mapping/tests/Functional/DownloadTablesWorkspaceSynapseTest.php
libs/input-mapping/tests/Helper/FakeDevStorageTableRewriteHelperTest.php
libs/input-mapping/tests/Helper/FakeDevStorageTagsRewriteHelperTest.php
libs/input-mapping/tests/Helper/RealDevStorageTableRewriteHelperTest.php
libs/input-mapping/tests/Needs/NeedsDevBranch.php
libs/input-mapping/tests/Needs/TestSatisfyer.php
libs/input-mapping/tests/ReaderTest.php

Fixes: https://keboola.atlassian.net/browse/PST-2366
Navazuje na úpravu output mappingu https://github.com/keboola/platform-libraries/pull/346
Před
Po

[input-mapping] CI tests speedup

---

libs/output-mapping/src/Mapping/AbstractMappingFromConfigurationDeleteWhereFilter.php
libs/output-mapping/src/Mapping/MappingFromConfigurationDeleteWhere.php
libs/output-mapping/src/Mapping/MappingFromConfigurationDeleteWhereFilterFromSet.php
libs/output-mapping/src/Mapping/MappingFromConfigurationDeleteWhereFilterFromWorkspace.php
libs/output-mapping/src/Mapping/MappingFromProcessedConfiguration.php
libs/output-mapping/src/Mapping/MappingFromRawConfigurationAndPhysicalData.php
libs/output-mapping/src/Mapping/MappingFromRawConfigurationAndPhysicalDataWithManifest.php
libs/output-mapping/src/Writer/FileItem.php
libs/output-mapping/src/Writer/Table/Source/LocalFileSource.php
libs/output-mapping/src/Writer/Table/Source/SourceInterface.php
libs/output-mapping/src/Writer/Table/Source/SourceType.php
libs/output-mapping/src/Writer/Table/Source/WorkspaceItemSource.php
libs/output-mapping/src/Writer/Table/Strategy/AbstractWorkspaceTableStrategy.php
libs/output-mapping/tests/Mapping/MappingFromConfigurationDeleteWhereFilterFromSetTest.php
libs/output-mapping/tests/Mapping/MappingFromConfigurationDeleteWhereFilterFromWorkspaceTest.php
libs/output-mapping/tests/Mapping/MappingFromConfigurationDeleteWhereTest.php
libs/output-mapping/tests/Mapping/MappingFromProcessedConfigurationTest.php
libs/output-mapping/tests/Mapping/MappingFromRawConfigurationAndPhysicalDataTest.php
libs/output-mapping/tests/Mapping/MappingFromRawConfigurationAndPhysicalDataWithManifestTest.php
libs/output-mapping/tests/Writer/File/FileItemTest.php
libs/output-mapping/tests/Writer/Table/Source/LocalFileSourceTest.php
libs/output-mapping/tests/Writer/Table/Source/WorkspaceItemSourceTest.php
libs/output-mapping/tests/Writer/Table/Strategy/AbstractWorkspaceTableStrategyTestCase.php

Part 1 of https://keboola.atlassian.net/browse/PST-2398
Připrava pro zapojení `delete_where` z configurace mappingu.
Obálka pro DeleteWhere filtr. Funkčně zatím nic nemění. To je až v dalším PR https://github.com/keboola/platform-libraries/pull/362

[output-mapping] delete where - part1

---

libs/output-mapping/src/Mapping/MappingFromConfigurationDeleteWhereFilterFromWorkspace.php
libs/output-mapping/src/Mapping/MappingFromProcessedConfiguration.php
libs/output-mapping/src/Storage/DeleteTableRowsOptionsFactory.php
libs/output-mapping/src/Storage/TableDataModifier.php
libs/output-mapping/src/Writer/Helper/DeleteWhereHelper.php
libs/output-mapping/src/Writer/Table/TableConfigurationResolver.php
libs/output-mapping/tests/Mapping/MappingFromConfigurationDeleteWhereFilterFromWorkspaceTest.php
libs/output-mapping/tests/Mapping/MappingFromProcessedConfigurationTest.php
libs/output-mapping/tests/Needs/TestSatisfyer.php
libs/output-mapping/tests/Storage/DeleteTableRowsOptionsFactoryTest.php
libs/output-mapping/tests/Storage/TableDataModifierTest.php
libs/output-mapping/tests/Writer/Helper/DeleteWhereHelperTest.php
libs/output-mapping/tests/Writer/Table/TableConfigurationResolverTest.php

Part 2 of https://keboola.atlassian.net/browse/PST-2398

[output-mapping] delete where - part2 - filters values_from_set, values_from_workspace

---

libs/output-mapping/src/Configuration/Adapter.php
libs/output-mapping/src/Writer/FileWriter.php
libs/output-mapping/tests/Configuration/File/Manifest/AdapterTest.php
libs/output-mapping/tests/Writer/File/Strategy/LocalTest.php
libs/output-mapping/tests/Writer/StorageApiFileWriterTest.php

Procisteni pro https://github.com/keboola/platform-libraries/pull/365

Remove TableWriter class improvement

---

libs/api-bundle/src/Security/ManageApiToken/ManageApiToken.php
libs/api-bundle/tests/Security/ManageApiToken/ManageApiTokenTest.php

Pridani `features` property na `ManageApiToken`, aby slo v controlleru delat snadno check na features manage tokenu.

feat: Add features on ManageToken

---

libs/sandboxes-service-api-client/src/Sandboxes/Legacy/Project.php
libs/sandboxes-service-api-client/src/Sandboxes/Legacy/Sandbox.php
libs/sandboxes-service-api-client/tests/Sandboxes/Legacy/SandboxTest.php
libs/sandboxes-service-api-client/tests/Sandboxes/SandboxesApiClientTest.php

https://keboola.atlassian.net/browse/PST-2453
Dropnuti podpory MLflow v `sandboxes-service-api-client`. Obdoba https://github.com/keboola/sandboxes-api-php-client/pull/87

PST-2453 Drop MLflow support

---

libs/input-mapping/azure-pipelines.tests.yml
libs/input-mapping/src/Helper/LoadTypeDecider.php
libs/input-mapping/tests/Helper/LoadTypeDeciderTest.php

DMD-67 disable clone load for external buckets, allow view load for tables with external bucksts

---

libs/input-mapping/composer.json
libs/output-mapping/composer.json
libs/staging-provider/composer.json
libs/staging-provider/src/Provider/Configuration/WorkspaceBackendConfig.php
libs/staging-provider/src/Provider/NewWorkspaceStagingProvider.php
libs/staging-provider/src/Provider/StorageApiWorkspace.php
libs/staging-provider/tests/CombinedProviderInitializerTest.php
libs/staging-provider/tests/InputProviderInitializerTest.php
libs/staging-provider/tests/OutputProviderInitializerTest.php
libs/staging-provider/tests/Provider/Configuration/WorkspaceBackendConfigTest.php
libs/staging-provider/tests/Provider/NewWorkspaceStagingProviderTest.php
libs/staging-provider/tests/Provider/StorageApiWorkspaceTest.php

https://keboola.atlassian.net/browse/PST-2471
Rozšíření zakládání workspace o loginType

feat: PST-2471 add loginType for creating workspace

---

docker-compose.yml
libs/configuration-variables-resolver/composer.json
libs/configuration-variables-resolver/phpstan.neon
libs/configuration-variables-resolver/src/UnifiedConfigurationResolver.php
libs/configuration-variables-resolver/src/UnifiedConfigurationResolverFactory.php
libs/configuration-variables-resolver/tests/Mockserver.php
libs/configuration-variables-resolver/tests/UnifiedConfigurationResolverFactoryTest.php
libs/configuration-variables-resolver/tests/UnifiedConfigurationResolverTest.php
libs/input-mapping/tests/Functional/DownloadTablesSynapseTest.php

Resolving shared codu i variables v rámci jedné třídy, bude se nahrazovat za custom resolving v rámci `job-queue-daemon`.
https://keboola.atlassian.net/browse/PST-2274

Create unified resolver for both variables and shared code

---

libs/api-bundle/src/RequestMapper/ArgumentResolver.php

Part of https://keboola.atlassian.net/browse/AJDA-87

chore: ArgumentResolver constants for HTTP error code and message

---

libs/permission-checker/src/Check/Ai/CanModifySessions.php
libs/permission-checker/tests/Check/Ai/CanModifySessionsTest.php

https://keboola.atlassian.net/browse/KAB-958

add permissions for WAII sessions

---

libs/input-mapping/composer.json

Povoleni Symfony 7 komponent v IM

chore[input-mapping]: Allow Symfony 7 components

---

azure-pipelines.tags.yml
azure-pipelines.yml
docker-compose.yml
libs/key-generator/.gitignore
libs/key-generator/LICENSE
libs/key-generator/README.md
libs/key-generator/azure-pipelines.tests.yml
libs/key-generator/composer.json
libs/key-generator/phpcs.xml
libs/key-generator/phpstan.neon
libs/key-generator/phpunit.xml.dist
libs/key-generator/src/CertificateSigningRequest.php
libs/key-generator/src/PemKeyCertificateGenerator.php
libs/key-generator/src/PemKeyCertificatePair.php
libs/key-generator/tests/CertificateSigningRequestTest.php
libs/key-generator/tests/PemKeyCertificateGeneratorTest.php
libs/key-generator/tests/bootstrap.php

https://keboola.atlassian.net/browse/PAT-257
Vyextrahovani https://github.com/keboola/storage-api-php-client/blob/master/tests/Utils/PemKeyCertificateGenerator.php do samostane lib.
Kod je ciste prevzaty, jen jsem prehodil vetsinu `assert` za regulerni vyjimky (protoze asserty se daji vypnout) a doplnil par checku tak, aby byl Phpstan happy. Nakonec jsme pridal par stupid testu jen aby tu bylo aspon neco.

PAT-257 Separate key-gen library

---

libs/k8s-client/composer.json
libs/k8s-client/phpstan.neon
libs/k8s-client/tests/KubernetesApiClientFacadeTest.php

https://keboola.atlassian.net/browse/PAT-259
Update base K8S lib na https://github.com/keboola/kubernetes-php-runtime/pull/6 - switch na `psr/log:^3.0`

[k8s-client] Update base K8S client lib

---

docker-compose.yml
libs/service-client/composer.json
libs/service-client/phpstan.neon
libs/service-client/phpunit.xml.dist
libs/service-client/src/ServiceClient.php
libs/service-client/tests/ServiceClientTest.php
libs/service-client/tests/ServiceTest.php

Update PHP requirement to min 8.3, update dev dependencies 
https://keboola.atlassian.net/browse/KAB-1062

dependencies update

---

libs/output-mapping/src/Storage/BucketCreator.php
libs/output-mapping/tests/Storage/BucketCreatorTest.php

https://keboola.atlassian.net/browse/AJDA-370
- `BucketCreator.createDestinationBucket()` threw exceptions when bucket already existed
- No handling for race conditions when multiple processes try to create the same bucket simultaneously
- Missing test coverage for race condition scenarios
- **Added race condition handling**: New `handleCreateBucketError()` method to process `ClientException` during bucket creation
- **Handle 400 errors**: When `createBucket()` fails with error code 400 (bucket already exists), verify bucket existence with `getBucket()`
- **Silent recovery**: If bucket exists during race condition, continue execution instead of throwing exception
- **Preserve error handling**: Non-race-condition errors still throw `InvalidOutputException`
- **Added …

fix[output-mapping]: AJDA-370 silencing the exception when creating a bucket (race condition)

---

Dockerfile
docker-compose.yml
libs/messenger-bundle/src/ConnectionEvent/AuditLog/BaseAuditLogEvent.php
libs/messenger-bundle/tests/ConnectionEvent/AuditLog/Project/ProjectPurgedEventTest.php

Fixes: https://keboola.atlassian.net/browse/AJDA-895

[messenge-bundle] BaseAuditLogEvent fix - admin is optional
